### ISSUE TITLE
🔐  Restricting assume roles to relevant trusted entities only

### ISSUE THREAD

**Issue by mTouhid** [ministryofjustice/nvvs-devops#143]
### User Story

As a… member of the CloudOps team 
I want to… restrict who can assume the AWS roles
So that… it improves the security

### Value / Purpose

It improves security and follows AWS trusted advisory guides

### Useful Contacts

Touhid, Rich, Aaron, Ed, Ky

### Additional Information

- [ ] SharedServicesCodeBuild
- [ ] CodeBuildPanwInbound
- [ ] CodebuildPanwPanoramaBaseConfig
- [ ] CodeBuildPanwGlobalProtect
- [ ] pttp-production-production-infra-shared-services-admin
- [ ] CodeBuildPanwPSN
- [ ] CodeBuildPanwEastWest
- [ ] CodeBuildPanwOutbound
- [ ] CodeBuildPanwPanorama
- [ ] CodeBuildPanwPanoramaPolicyConfig
- [ ] staff-device-production-infra-code-build-panw-sop-oci-access

Shared Services
- [ ] pttp-global-ima-snmp-shared-services-admin
- [ ] pttp-global-ima-ds-shared-services-admin
- [ ] pttp-david-infra-shared-services-admin 

Pre-Prod
- [ ] CodeBuildPanwEastWest
- [ ] CodeBuildPanwGlobalProtect
- [ ] CodeBuildPanwInbound
- [ ] CodeBuildPanwOutbound
- [ ] CodeBuildPanwPanorama
- [ ] CodebuildPanwPanoramaBaseConfig
- [ ] CodeBuildPanwPanoramaPolicyConfig
- [ ] CodeBuildPanwPSN
- [ ] CodeBuildTGW
- [ ] pttp-pre-production-infra-shared-services-admin
- [ ] SharedServicesCodeBuild
- [ ] staff-device-pre-production-infra-code-build-panw-sop-oci-access

Development
- [ ]CodeBuildPanwPanoramaPolicyConfig
- [ ]staff-device-development-infra-code-build-panw-sop-oci-access
- [ ] CodeBuildPanwPanorama
- [ ] CodeBuildPanwOutbound
- [ ] CodeBuildPanwEastWest
- [ ] CodeBuildPanwPSN
- [ ] CodeBuildTGW
- [ ] pttp-development-infra-shared-services-admin
- [ ] CodeBuildPanwGlobalProtect
- [ ] CodebuildPanwPanoramaBaseConfig
- [ ] CodeBuildPanwInbound
- [ ] SharedServicesCodeBuild

### Definition of Done

- [ ] Roles will have specific trusted entities in the trust relationship 
- [ ] Create documentation with details

**Comment by ASTRobinson** [comment]
Pre-Prod: 

CodeBuildPanwEastWest
CodeBuildPanwGlobalProtect
CodeBuildPanwInbound
CodeBuildPanwOutbound
CodeBuildPanwPanorama
CodebuildPanwPanoramaBaseConfig
CodeBuildPanwPanoramaPolicyConfig
CodeBuildPanwPSN
CodeBuildTGW
pttp-pre-production-infra-shared-services-admin
SharedServicesCodeBuild
staff-device-pre-production-infra-code-build-panw-sop-oci-access

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/143?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson
