### ISSUE TITLE
📌  SPIKE - Improve dashboarding experience

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/nvvs-devops#146]
### User Story

As a user of the Monitoring and Alerting system (IMAP)
I want a simple way to create dashboards
So that I can actually create a dashboard without being a Grafana 🤓

### Value / Purpose

The feedback that it is hard edit and create dashboards
It is a convoluted process to store as code, can this be improved?

### Useful Contacts

Rich, Emile

### Additional Information

Look at 
- https://grafana.com/blog/2020/02/26/how-to-configure-grafana-as-code/
- https://grafana.com/blog/2018/09/13/everything-you-need-to-know-about-monitoring-mixins/

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Gary-H9** [comment]
The core purpose of IMAP has now changed from a solution which the wider business was encouraged to use, to one which we solely expect to be used within our team. That aside however, the newly designed IMAP no longer required users store their dashboards in code. 

We have updated the landing page of monitoring to reflect this and have also updated the [NVVS DevOps page](https://github.com/ministryofjustice/nvvs-devops/pull/313) with respect to this.
