### ISSUE TITLE
📚 Add GitHub issue checklist template for onboarding new joiners

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/nvvs-devops#203]
### User Story

As a new starter in the Cloud Ops team
I want to have a list of the things I need
So that I have all the access and tooling required to do my job.

### Value / Purpose

Improve onboarding experience
Make sure we have all the steps required e.g. to get access to our DHCP portals in each environment written down

### Useful Contacts

Rich B

### Definition of Done

- [ ] [Documentation](https://ministryofjustice.github.io/cloud-operations) has been written / updated 
- [ ] Issue template is available https://github.com/ministryofjustice/cloud-operations/issues/new/choose

**Comment by juddin927** [comment]
added a draft checklist page to the team github page and pushed that as a new branch here. https://github.com/ministryofjustice/nvvs-devops/commit/8908cd7dd3525a0e9ad52813fdb32753bc173be4
