### ISSUE TITLE
🌱 SPIKE: Migrate and containerise PHP-IPAM application

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/nvvs-devops#204]
Timebox: 1 day

### User Story

As a cloud operations engineer
I want to facilitate the modernising of legacy applications
So that we can close down AWS accounts and simplify operations for Technology Services

### Value / Purpose

💰 The current system is overprovisioned 🌱 Reduce our cloud costs
⏩ ClickOps'd - There is no automation so no testing of updates etc
📝 Can be documented as Code

### Useful Contacts

Rich B, Touhid 

### Additional Information

PHP-IPAM needs to be migrated out of the current AWS account (Workplace Tech) as that will be closed down soon.
Since there is no networking requirement (no TransitGW requirement) we can deploy this system to Cloud Platform which means there will be less management overhead for the TechOps teams. 
We already have deployed our CloudOps bot so have experience already.

### Definition of Done

- [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Gary-H9** [comment]
Turned this into a spike to spin up multiple other tickets and an epic. 

Containers already [this](https://hub.docker.com/r/phpipam/phpipam-www.).
