### ISSUE TITLE
🔋  Allow capacity team access to AWS account Cost Explorer and usage reports

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/nvvs-devops#206]
### User Story

As a capacity manager
I expect to be able to view and download cost reports from Cloud based services
So that this data can be reviewed, analysed and improvements can be suggested

### Value / Purpose

Provide access and visibility to capacity team for billing data, this information can be exported out to CSV.
![image](https://user-images.githubusercontent.com/20583399/176432397-07635871-3c7d-4499-be28-4f287cf43278.png)

### Useful Contacts

Rich B, Gary

### Additional Information

We need to decide on how we give access. IAM across multiple accounts (we would need code to manage and we would need to manage their account 🙁) or SSO against all, but requires GitHub accounts for their team( which may not be a bad thing considering how much information that will open up)

[AWS Cost Explorer guide](https://aws.amazon.com/aws-cost-management/aws-cost-explorer/)

### Definition of Done

- [ ] A capacity team member has been given access and has been shown how to gain access.

**Comment by Gary-H9** [comment]
Consider the use of the root account in this piece of work.

**Comment by mitchdawson1982** [comment]
Access for Neil Pegg and or Team
