### ISSUE TITLE
📊 Total Reservations

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops#219]
### User Story

As a CloudOps Engineer
I want to know the total number of reservations served (today / this week / this month / all time)
So that I can provide this information to the SLT / have historic data for the portal in reference to this. 

### Value / Purpose
Demonstrates the value of the portal. Provides a source for historic data. 

### Definition of Done
- [ ]  total reservations served (today) on the /api
- [ ]  total reservations served (this week) on the /api
- [ ]  total reservations served (this month) on the /api
- [ ]  total reservations served (all time) on the /api

**Comment by bagg3rs** [comment]
Total reservations https://monitoring-alerting.staff.service.justice.gov.uk/d/9QAN_V67z/dhcp-lease-statistics?orgId=1
