### ISSUE TITLE
⏩  Migrate Transit Gateway Deployment to GitHub Actions

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/nvvs-devops#240]
### User Story

As a Cloud Operations Engineer
I want to standardise the CI/CD deployment of our services
So that troubleshooting and visibility for all teams (as others need to make changes) of the status of the deployment.

### Value / Purpose

The current pipeline doesn't seem to use Parameter Store for its PAT token and that has expired https://github.com/ministryofjustice/deployment-tgw/issues/135
We have decided to move to GitHub Actions.
This will also give other teams the ability to see the status rather than asking team members with access to the Shared account.
We should rename the repository to be clearer about what it is.

### Useful Contacts

Rich B, Touhid, Andy C

### Additional Information

Repo https://github.com/ministryofjustice/deployment-tgw/

### Definition of Done

- [ ] Remove TGW CodePipeline
- [ ] README has been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by mitchdawson1982** [comment]
Andy C is going to start looking into this and will fall back to CloudOps if required.

**Comment by bagg3rs** [comment]
Issue raised on TGW repo https://github.com/ministryofjustice/deployment-tgw/issues/156
