### ISSUE TITLE
📖 Improve our product docs

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/nvvs-devops#246]
### User Story

As a Cloud Operations Engineer
I want frequently requested information for product listed on our public documentation.
So that we can improve support and knowledge transfer.

### Value / Purpose

Store common service information in a text-based format which can be read by humans and machines.

### Useful Contacts

RB, Rachel

### Additional Information

Have an additional docs page before hitting the repository with information that is useful for Product and Service managers Stop questions before they happen

https://ministryofjustice.github.io/cloud-operations/#our-products
This should go to e.g. a DNS page with e.g.

- Dashboard/Portal link
- AzureAD group, required to access portal dashboard etc
...

### Definition of Done

- [x] DNS see [here](https://ministryofjustice.github.io/cloud-operations/documentation/products/dns.html#dns-overview)
- [x] DHCP
- [ ] IMAP
- [x] NACS
- [ ] Log Shipping
- [x] PKI
- [ ] SMTP
- [ ] Tech Docs Monitor

**Comment by Gary-H9** [comment]
@bagg3rs hey, since this is documentation we have pointed this as a 1. Can we make the DoD a bit more specific so we get the most value from this?

**Comment by bagg3rs** [comment]
Have added examples and added checklist for all products!
