### ISSUE TITLE
📌 ⏩  Local GitHub Runners for development

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/nvvs-devops#256]
Timebox 0.5 day
### User Story

As a CloudOps Engineer
I want to develop locally on GitHub Actions runner
So that I can get faster feedback 

![Demo](https://github.com/nektos/act/wiki/quickstart/act-quickstart-2.gif)

### Value / Purpose
Feedback, Feedback, Feedback

### Additional Information

[Local Runner repo](https://github.com/nektos/act) 

Local Task Runner - I love [make](https://en.wikipedia.org/wiki/Make_(software)). However, you can use the GitHub Actions defined in your .github/workflows/ to replace your Makefile?!

### Definition of Done

- [ ] Our team documentation has been written / updated
- [ ] ⚡️ talk learntech

**Comment by mitchdawson1982** [comment]
Maybe look to implement this on  a friday learn tech.
