### ISSUE TITLE
✨  Add editor.config to vscode to get consistent YAML across team members

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/nvvs-devops#274]
### User Story

As a CoP
I expect we tab and space the same
So that our YAML is consistent 🕙 

### Value / Purpose

Tabs vs Spaces ¯\_(ツ)_/¯ as long as we are consistent!

### Additional Information

We can look at YAML linting

### Definition of Done

- [ ] editor config is created
- [ ] applied to all devs machines 
- [ ] applied to repo's

**Comment by Gary-H9** [comment]
We've elected to close this issue with no action, we haven't hit this as an issue in a while and think it should be caught by the YAML linters in the event it's needed.
