### ISSUE TITLE
:truck: Rebrand to NVVS DevOps

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/nvvs-devops#287]
### User Story

As an NVVS DevOps team member
I want to see our new team name used on everything! (NVVS DevOps)
So that people know who we are rather than using numerous previous names (CloudOps / NCI / Core Network Services etc etc)

### Value / Purpose

The sooner we do this the less confusing it will be for other teams moving forward as people start to learn our new name.

### Useful Contacts

NVVS DevOps

### Additional Information

Places to update team name:

Slack Channels: #mojo-cloud-ops / #ask-cloud-ops > NVVS-DevOps
Service Now; Team name needs updating and team membership also requires updating.
GitHub Pages: https://ministryofjustice.github.io/cloud-operations/#cloud-operations > NVVS DevOps
GitHub: Individual repo readme's require checking for references to the CloudOps team etc. 
Zenhub workspace name

### Definition of Done

- [x] Slack Channels have been updated
- [x] GitHub README's has been updated
- [x] GitHub Pages have been updated
- [ ] ServiceNow has been updated
- [x] PagerDuty has been updated
- [x] update codeowners files

**Comment by Gary-H9** [comment]
PagerDuty name should be updated [here](https://moj-digital-tools.pagerduty.com/teams/PGKWSHP/users) too.

**Comment by ASTRobinson** [comment]
PagerDuty rebranded

**Comment by ASTRobinson** [comment]
All rebranding (with the exception of ServiceNow which is in hand and beyond our control) has now been completed (RIP Cloud-Ops, Long live NVVS DevOps)
