### ISSUE TITLE
🗡SPIKE NACS - TLS-CLIENT-CERT* Custom Attribute

### ISSUE THREAD

**Issue by mitchdawson1982** [ministryofjustice/nvvs-devops#330]

**Comment by mitchdawson1982** [comment]
Justin Fielding conveyed a requirement for NACS to authenticate printers via an attribute that is not currently in the TLS-CLIENT-CERT dictionary. We need to conduct a spike to validate if adding a custom attribute to the dictionary is possible/supportable.
ATOS are going to setup NDES to support the new Xerox printers and issue certs via a specific certificate template.

# Freeradius Archive
https://freeradius-users.freeradius.narkive.com/7rCtRveh/certificate-information

The certificates do have a field 'Certificate Template Information' but it doesn't seem to be exposed in the 'TLS-Cert' or 'TLS-Client-Cert' attributes we see exposed in cloudflare logs or as attributes to use in policies via the GUI.

**Comment by jennycasanova** [comment]
Justin has confirmed that he has nothing further to add other than what he has already provided to Mitch.
The spike to see if it viable is urgent as this will steer further plans and if an alternative solution needs to be considered.
Justin has suggested half a day.

**Comment by mitchdawson1982** [comment]
I have asked Justin to attempt a test of the feature in the dev environment, awaiting feedback.

**Comment by mitchdawson1982** [comment]
We have been unable to get a test to succeed and we are in agreement that we have reached the end of the line in terms of getting custom attributes to work on free radius.
