### ISSUE TITLE
🧹 Tidy up EBS volumes (Dev, Pre-Prod, Prod)

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops#337]
Establish if the remaining EBS volumes (18) in Dev are now redundant and can be deleted. 

`aws ec2 describe-volumes --filters Name=status,Values=available | grep Attachment | wc -l` 

Repeat this process for Pre-Production and Production.

**Comment by tomwells98** [comment]
Are there costs involved with this?
