### ISSUE TITLE
SPIKE - Grafana alert for wired only errors on NAC

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#343]
**As a DevOps engineer** I want to investigate the possibility of having alerts produced through Grafana that identify when a rogue device is attempting to access our Network through a wired access point only.

Value/Purpose
As an engineer I want to distinguish wired only access errors to allow me to be notified when a device is unable to access the network through a wired cable.  

Additional information
As an engineer, once I have been notified of the error I need to establish a process to deal with these errors effectively across the MOJ estate.  This task will not form part of this spike as this needs to be addressed separately.

**Comment by mitchdawson1982** [comment]
Spike completed we have a way forward using the freeradius logline module. 
https://wiki.freeradius.org/guide/eduroam-logging
