### ISSUE TITLE
 Multiple devices across 3 wings unable to access IT services

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#363]

**Comment by mitchdawson1982** [comment]
Every single subnet on this site has valid leases. 
![image](https://github.com/ministryofjustice/nvvs-devops/assets/86007219/2b8005f8-1580-45aa-befb-62276f9b3168)

**Comment by mitchdawson1982** [comment]
This is likely a local LAN issue, DHCP service is functioning as expected.
