### ISSUE TITLE
SPIKE - AWS To disable inactive pipelines

### ISSUE THREAD

**Issue by mitchdawson1982** [ministryofjustice/nvvs-devops#365]
AWS have made the decision to disable pipelines that have been inactive for 30 days or more.

# Pipelines in scope
- Polling Pipelines (A polling pipeline is defined as a pipeline that has at least one source action configured to poll for changes.)

# Pipelines not in scope
Pipelines that only use Amazon EventBridge rule, or AWS CodeStar Connections, or webhooks to trigger the pipeline will not be affected. Additionally, any active pipeline will also not be affected.

**Comment by mitchdawson1982** [comment]
---------- Forwarded message ---------
From: 'Amazon Web Services, Inc.' via AWS - notifications <aws@digital.justice.gov.uk>
Date: Fri, 28 Apr 2023 at 08:48
Subject: [Action may be required] AWS CodePipeline is disabling polling in inactive pipelines [AWS Account: 068084030754]
To: <aws+mojofficial-dev@digital.justice.gov.uk>
Cc: <griton@amazon.com>


Hello,

You are receiving this message because you have one or more polling pipelines in your account. A polling pipeline is defined as a pipeline that has at least one source action configured to poll for changes. The AWS CodePipeline team will be disabling polling in inactive pipelines effective May 25, 2023. An inactive pipeline is defined as one that has not had a pipeline execution started in the last 30 days. Inactive pipelines that only use Amazon EventBridge rule, or AWS CodeStar Connections, or webhooks to trigger the pipeline will not be affected. Additionally, any active pipeline will also not be affected.

We recommend that you update to use Amazon EventBridge, or AWS CodeStar Connections, or webhooks as the trigger mechanism for your source. Follow the instructions in the documentation[1] for making this change. Changing your pipeline from polling to event based will improve performance for pipeline executions by ensuring they respond to source changes quicker.

If you have questions about this change, the AWS Support Team is available on re:Post [2] and via Premium Support [3].

[1] https://docs.aws.amazon.com/codepipeline/latest/userguide/update-change-detection.html
[2] https://repost.aws/tags/TAD_CcYa8ASIKYqZ_uXiwwgA/aws-codepipeline
[3] https://support.console.aws.amazon.com/support

Sincerely,
Amazon Web Services

Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210

---
Reference: https://phd.aws.amazon.com/phd/home?region=us-east-1#/event-log?eventID=arn:aws:health:global::event/CODEPIPELINE/AWS_CODEPIPELINE_OPERATIONAL_NOTIFICATION/AWS_CODEPIPELINE_OPERATIONAL_NOTIFICATION_e2736fe38a3e5869b49adbb835bbee22fc924b0edc30e8c57c7080e2c7f4780f&amp;eventTab=details

**Comment by juddin927** [comment]
Following pipelines code are not in our repo 
- GlobalProtect[NEVER USED]
- GlobalProtect-ASG
- Panorama-Policy-as-Code [NEVER USED]
- Panorama-PolicyAsCode-Prod[NEVER USED]
- Panorama
- SOP-OCI-Access
- PSN-Access
- TGW

Look like these pipelines are used by other team and we are not responsible for the infrastructures it manages. We need to have a discussion to agree on the next steps

**Comment by babatundek** [comment]
To be done after Ticket 63

**Comment by juddin927** [comment]
as far as spike concerns this ticket is completed we need to create relevant tickets to take on works to address the findings in this ticket.
