### ISSUE TITLE
READ ME update - Container image monitoring

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#369]
Dependabot currently does not support a container image monitoring solution.  This therefore cannot currently be automated through a dependabot and therefore this process needs to be done manually.

GitHub document page needs to be updated as a read me document to confirm as a reminder that this is a manual task.

**Comment by juddin927** [comment]
Created a new label in github as "known_issue" and added the label to the original ticket. This ticket is to ensure that we update the readme with the information on manual update for the container image monitoring.

**Comment by satishgummadellimoj** [comment]
https://github.com/ministryofjustice/staff-device-dns-dhcp-admin/pull/711
