### ISSUE TITLE
Upgrade NAC package version 1.1.1.t-r2 to new version 1.1.1u-r1

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#371]
The Openssl package name has changed in Alpine 3.16 and as a result the build is failing for the NACs server

As an engineer I need to update the existing package version from 1.1.1.t-r2 to the new version 1.1.1u-r1 which will ensure the build starts working again and stops failing

This ticket is linked with the work being carried out in ticket 63 

https://github.com/ministryofjustice/network-access-control-server

https://pkgs.alpinelinux.org/packages?name=openssl&branch=v3.16&repo=main&arch=x86_64&maintainer=

**Comment by juddin927** [comment]
completed local build with the openssl version 1.1.1u-r1  all test passed successfully. PR raised will roll in to prod

**Comment by juddin927** [comment]
Production build has completed with the new version of openssl.
