### ISSUE TITLE
DHCP - secret group code update

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#374]
Added this ticket as a placeholder for further details to be included from devops.

Code update required in DHCP secret groups as an issue was found which has been temporary fixed but needs a permanent code change.

**Comment by juddin927** [comment]
DHCP container missing default outbound allow(0/0) but 10.180.80.0/22

**Comment by juddin927** [comment]
raised a PR to include all out on port 68 to 0/0. merged and updated in Production.
