### ISSUE TITLE
Delete unused pipelines

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#380]
As an engineer I need to have access to all pipelines required for my role but ensure that unused pipelines are removed so the traffic flow is not interrupted.

Housekeeping

**Comment by juddin927** [comment]
List of pipelines that need deleting 
GlobalProtect[NEVER USED]
Panorama-Policy-as-Code [NEVER USED]
Panorama-PolicyAsCode-Prod[NEVER USED]

**Comment by juddin927** [comment]
Panorama-Policy-as-Code [NEVER USED] showing a dependency will review that and delete

**Comment by satishgummadellimoj** [comment]
@juddin927 , Panorama-Policy-as-Code was run 1 year back in our environments

**Comment by satishgummadellimoj** [comment]
codepipeline/GlobalProtect-ASG was run 4 months ago

**Comment by satishgummadellimoj** [comment]
Moving it to done as all other pipelines are used now.
