### ISSUE TITLE
Upgrade of SOP-OCI-Access

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#383]
As an engineer we need to ensure our pipelines are being used in the latest format. It has been established that the SOP=OCI-Access needs to be upgraded in the correct source code in Gibhub.

This pipeline is used by the Gateway team and the contact for that team is Thomas.Annell@justice.gov.uk

Link ticket with - #365

**Comment by juddin927** [comment]
upgraded the source action to github version 2 to use  
Arn
arn:aws:c

**Comment by juddin927** [comment]
Background: These pipelines are created over 2 year ago using this [repo](https://github.com/ministryofjustice/PaloAlto-pipelines) which is very much out of date and tightly coupled with other resources which are part of PaloAlto product suites in the same state file. After reviewing the code it looked appropriate not try reusing the same code as there are couple of issues
- We do not have the TFVARs that is required to work on the code 
- Not having background of the other resources on the same state file.
- Hardcoded value which are sensitive in nature.

We collectively agreed to proceed with upgrading the GitHub source action to GitHub version 2 using NVVS codestar connection on the AWS console and unblock these pipelines. As it would not add much of a value having the immutability(DR perspective) of the AWS CodePipleines as its a managed regional service offering from AWS.  And future aspiration is to move these pipelines to Github Actions.
