### ISSUE TITLE
NACS certificate renewal (DEV)

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#389]
1. Devops guys create .csr (certificate signing request) on the NACS backend
2. This file will be send to Matt White and the MOJ PKI team
3.This team will either create or ask Entrust to create a new certificate
4.New certificate will be sent to devops
5.New certificate would be installed to NACS dev environment first (on NACS backend by devops)
6.LAN/WIFI engineers would do testing to ensure that all is working
7.New certificate would be installed to NACS prod environment (on NACS backend by devopsMore details TBD. 

Useful Contacts:
-  Emile Swarts (a contractor who helped build NACS but should still be available in the MoJ)
-  Mitchel Dawson 
-  Matt White

**Comment by jennycasanova** [comment]
We need to do the certificate signing request.  Matti is reaching out to Emilie to provide context of how to do this.

**Comment by jennycasanova** [comment]
Comments from Matti after discussion with Emile:
Spoke briefly with Emile about this. So it seems the private key and certificates are stored on secured S3 bucket. We can create a new CSR with Openssl and this should create a private key which we then would replace on the S3 bucket (dev). New cert would be added there too when it’s done on Entrust by using the CSR.

I think this can be tested when ever and when you are happy with the results (i.e. new private key was created and we know where the old key and cert is located), we can create the new cert and test on Dev. 

The script which was used to do the last one from Emile:


csr.sh
#!/bin/bash

set -e

#openssl genrsa -out radsec.key
openssl req -new -key radsec.key -out radsec.csr -config csr.cnf
#openssl x509 -req -days 365 -in radsec.csr -signkey radsec.key -out radsec.crt -extensions req_ext -extfile csr.cnf
csr.cnf
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
C="GB"
O="Ministry of Justice"
OU="Digital & Technology"
CN="radsec.network-access-control.service.justice.gov.uk"
emailAddress=certificates@digital.justice.gov.uk

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = radsec.dev.network-access-control.service.justice.gov.uk
DNS.2 = radsec.prep.network-access-control.service.justice.gov.uk

**Comment by tomwells98** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NVVS-DevOps-622a0b371800e400133bb924/issues/ministryofjustice/nvvs-devops/389?planning-poker) with Zenhub @juddin927 @smjmoj @darey-io @satishgummadellimoj

**Comment by darey-io** [comment]
CSR and private key for Dev has been created. It is now in blocked until Matt becomes available as he is currently busy on DHCP work.

What is needed

1. Replace private key in parameter store
2. Send the CSR to Matt
3. Matt to raise the certificate request using the CSR

**Comment by juddin927** [comment]
EAP server certificate has been renewed in NAC DEV environment
