### ISSUE TITLE
DHCP scope review - Non res wifi

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#390]
The list has been provided of the sites that fall part of the non-res wifi project.  The DHCP scope should have already been done for all of these site including any subnets.

The project would like a check done that the details they have are correct as what has been set up on the portal.

The first site will be going live on 24.07.23 so this ticket needed to be completed prior to this date and allowance for any changes that need to take place if the data does not match up.

Contact for this ticket is Russell Sivalingam

[https://app.zenhub.com/files/407467657/da0f9569-40eb-4895-ae8f-514a0df697c4/download](https://app.zenhub.com/files/407467657/da0f9569-40eb-4895-ae8f-514a0df697c4/download)

**Comment by satishgummadellimoj** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NVVS-DevOps-622a0b371800e400133bb924/issues/ministryofjustice/nvvs-devops/390?planning-poker) with Zenhub @satishgummadellimoj

**Comment by tomwells98** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NVVS-DevOps-622a0b371800e400133bb924/issues/ministryofjustice/nvvs-devops/390?planning-poker) with Zenhub @satishgummadellimoj @smjmoj @juddin927 @darey-io

**Comment by darey-io** [comment]
Contacted Russell Sivalingam to begin this discussion. Still awaiting a reply. Will chase up today

**Comment by juddin927** [comment]
We have checked the specs on the doc attached in the tickets please find the updated one with our comments in below documents 
https://docs.google.com/spreadsheets/d/1HuyeaO786DnYiFIqe7gX4WIU9hsIj0tt_A6fmDxmtdg/edit#gid=0
