### ISSUE TITLE
Check reachability for servers

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#405]
**What:** 
Linked to incident ticket 403

The reachability for these four servers needs to be tested so we don't send queries if we can't reach them. 

Name:	azure.hmpp.root
Address: 10.40.144.196
Name:	azure.hmpp.root
Address: 10.40.0.133
Name:	azure.hmpp.root
Address: 10.40.64.133
Name:	azure.hmpp.root
Address: 10.40.128.196

**Comment by juddin927** [comment]
Completed reachability checks and updated the records
