### ISSUE TITLE
Review terraform code & scale down configuration for DNS containers

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#406]
**As an engineer I need** to review the terraform code to consider the following:

- Review the auto scaling group (ASG) configuration.
- 
- Examine the scale-in policies.
- 
- Evaluate the cool down period.

**As an engineer I need** to scale down the configuration for the DNS containers and make this process automated so it will scale up when required but also scale back down when the need is no longer required.

**Comment by smjmoj** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NVVS-DevOps-622a0b371800e400133bb924/issues/ministryofjustice/nvvs-devops/406?planning-poker) with Zenhub @smjmoj

**Comment by satishgummadellimoj** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NVVS-DevOps-622a0b371800e400133bb924/issues/ministryofjustice/nvvs-devops/406?planning-poker) with Zenhub @satishgummadellimoj

**Comment by tomwells98** [comment]
This can be done manually a the moment
