### ISSUE TITLE
SPIKE - DHCP - Automation to remove unrequired reservations 

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#408]
Following the recent incident where a change was carried out that caused DHCP issues, a change was carried out today on one site - HMP Feltham to remove the a03 domain. 

The background being: 

Due to the decommissioning of the Quantum Active Directory and the removal of the DNS Servers, there is a need to remove references to a03.wp360g.svcs.hp.com from any MOJ infrastructure.  This is because we are no longer reliant on a03 domain post the removal of DXC services.  This is to support the EXIT of the DXC contract, the exit of which is a phased approach.

We will be replacing the DNS suffix from local subnets as dom1.infra.int 

The changes need to be completed prior to the removal of the AO3 domain (DXC) by DXC as part of the phased exit.  The AO3 domain and express route via DXC is due to be removed by the end of the week (13th) hence the need to expedite.  

To ensure we are able to meet our contractual obligations, we need to make this change this week to support the agreed plan.  This also addresses the incident INC2107387.  The incident resolution was a temporary fix raised under emergency.  This change will ensure they are resolved strategically and long term, thus this needs to be applied under an expedite.

It has been noticed that there are hundreds of reservations for each site and we therefore need to remove the DNS suffix from each reservation in addition to carrying out the change above.

As a manual task this will be very time consuming as it will take approximately 3 minutes per reservation and there will be thousands of them in total.

We need a solution to automate removing this reservations to avoid having to do this task manually.

We have been asked to prioritise this spike due to the background and the number of people involved in this incident.

Contact for this ticket is Matti Sysmalainen.

**Comment by tomwells98** [comment]
More of a cosmetic change
