### ISSUE TITLE
🧪SPIKE DHCP search function 

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#409]
User Story: 
As an engineer I want to be able to quickly and easily search for sites on the DHCP portal so that I am not slowed down in troubleshooting or carrying out my work.
As a DevOps engineer I want to ensure that the ability to search for sites via name on the DHCP portable is scalable so that usability is not impaired as more sites are put onto the portal.

Context:
There is currently no inbuilt search function on the DHCP portal. This means that for engineers to find a site they need to to use control F and rely on their browser to provide this function. This currently works but there is a limited number of sites on the portal and additionally will not be able to query any underlying databases. This means that we cannot add pages onto the portal as the browser search function cannot search in-between pages. This means our current solution limits us to having one page on the portal. 

**We want to look to provide a basic search function with the option to provide more advanced features later on** 

To Do: 

- [x] We have a search function on the NACS portal.  Can we reuse any of this on the DHCP portal? 
- [x] If we cannot reuse anything look into different methods to provide this feature and quantify the work involved
- [x] Attach findings onto this ticket 

![image.png](https://images.zenhubusercontent.com/6315cc531779472e7e02f05f/19c132bd-4a2b-4ba5-8ad1-884baae9d696)

![image.png](https://images.zenhubusercontent.com/6315cc531779472e7e02f05f/86fc62fe-3ed7-446a-a680-4b9d8a9870e2)

This ticket is linked to another ticket to add a description on the subnets to the DHCP portal.

The NAC portal has this required search function and this works well.  Please replicate for DHCP

**Comment by tomwells98** [comment]
Tom and Jenny to speak with Mary and engineers for further details and requirements. e.g. what do we need exactly to be pulled up in the search function?

**Comment by babatundek** [comment]
Time box - 3 days actual time (not elapsed)

**Comment by juddin927** [comment]
KMS access added to the assume role and tested its working now.
Copied Database dump to s3 bucket

**Comment by juddin927** [comment]
During the SPIKE, we addressed the following areas:

1. Automated the construction of the Bastion.
2. Established cross-account S3 access from the bastion for all environments.
3. Developed a mechanism for generating database dumps across all environments.
4. Introduced search functionalities on DHCP, utilising site ID, Name, and Subnet CIDR in a Local Build.

Next Steps:

**Conduct Testing:**

1. Automated Build and User Acceptance Testing (UAT).
2. Proceed with Releases:
- Deploy to Development & Pre-Production.
- Execute Production Release

**Comment by juddin927** [comment]
[https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/525](url)

**Comment by juddin927** [comment]
[Release the feature in to development and pre-production ](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/525)

**Comment by juddin927** [comment]
#525
