### ISSUE TITLE
NACS Prod Cert

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#415]
Devops guys create .csr (certificate signing request) on the NACS backend
This file will be send to Matt White and the MOJ PKI team
3.This team will either create or ask Entrust to create a new certificate
4.New certificate will be sent to devops
5.New certificate would be installed to NACS dev environment first (on NACS backend by devops)
6.LAN/WIFI engineers would do testing to ensure that all is working
7.New certificate would be installed to NACS prod environment (on NACS backend by devopsMore details TBD.
Useful Contacts:

Emile Swarts (a contractor who helped build NACS but should still be available in the MoJ)
Mitchel Dawson
Matt White

**Comment by juddin927** [comment]
Deployment plan for NAC server EAP certificate renewal


 Update the private key password with the new password in the SSM parameter store(EAP_PRIVATE_KEY_PASSWORD) for Production also save the old one securely
 Rename the production EAP certificate in the Production NAC certificate S3 bucket to OLD-server.pem
 Prepare the signed certificate in .pem format with the private key in it
 Delete the server.pem certificate from the NAC admin portal 
 Upload the server.pem certificate prepared in step 3 in the NAC admin portal.
 


Backout plan 
Update the private key password(EAP_PRIVATE_KEY_PASSWORD) with the OLD password in the SSM parameter store for Production
Download the old OLD-server.pem certificate from the production NAC certificate S3 bucket
Delete the server.pem certificate from the NAC admin portal
Upload the OLD-server.pem certificate in NAC admin portal

**Comment by juddin927** [comment]
Renewal completed successfully on 19th of August
