### ISSUE TITLE
NACS failed log in

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#422]
What: 
Currently we are seeing an issue where NACS may not authenticate on the first try and need a few attempts to work. We suspect the issue may be cause by ATOSS PKI but need to carry out investigative work on our end.

INC2149125 has been raised to track the issue.

**Comment by juddin927** [comment]
(20187) eap_tls: Starting OCSP Request
(20187) eap_tls: ocsp: Using responder URL "[http://pkicrlaia.lexlive.internal:80/ocsp](http://pkicrlaia.lexlive.internal/ocsp)"
(20187) eap_tls: ERROR: ocsp: Couldn't get OCSP response

**Comment by juddin927** [comment]
Then second authentication right away:
(20202) eap_tls: Starting OCSP Request
(20202) eap_tls: ocsp: Using responder URL "[http://pkicrlaia.lexlive.internal:80/ocsp](http://pkicrlaia.lexlive.internal/ocsp)"
"	This Update: Aug 10 09:45:51 2023 GMT"
"	Next Update: Aug 11 22:05:51 2023 GMT"
(20202) eap_tls: ocsp: Cert status: good
(20202) eap_tls: ocsp: Certificate is valid

**Comment by juddin927** [comment]
created a new metric for "E[AP TLS OCSP Error"](https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/mojo-production-nac-server-log-group/edit-metric-filter/EAP$2520TLS$2520OCSP$2520Error)

**Comment by juddin927** [comment]
C:\Users\bkw65w>nslookup pkicrlaia.lexlive.internal
Server:  UnKnown
Address:  10.184.96.0
Non-authoritative answer:
Name:    pkicrlaia.wip.lexlive.internal
Address:  10.171.71.159
Aliases:  pkicrlaia.lexlive.internal

**Comment by juddin927** [comment]
also "Sent Access-Reject" metric could be capturing EAP-TLS failure 
 (94312) Sent Access-Reject Id 200 from 10.180.108.188:1812 to 194.33.203.41:38349 length 20

**Comment by juddin927** [comment]
to conclude container IP is the egress IP for traffic going to OCSP


so if there is a FW or network appliance in the traffic path we can trace for destination 10.171.71.159:80( for all ocsp lookup on http)

source would be from any of these subnet that container are running
10.180.109.128/25
10.180.108.128/25
10.180.110.128/25
