### ISSUE TITLE
VPC Flow Logs

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#423]
What: 
Ronak has contacted us as access logs for management vpc on prod seems to be broken. VPC is below:
vpc-0de4ba808005983d2 / Management VPC

**Comment by juddin927** [comment]
I had a look at the VPC flow log issue in management VPC the reason it was not working as the referenced role in the flow log config does not exists. As this is not amendable I have re-created a vpc flow subscription with the new role I have created. It should start collecting logs from now on. 

https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/$252Faws$252Fvpc-flow-log$252Fvpc-0de4ba808005983d2
