### ISSUE TITLE
🔊 Spike: Logging capability

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/nvvs-devops#43]
Timebox: 0.5 days

## User Story
As a CloudOps engineer
I need to understand what logging options are available
So that I can build a logging platform to help improve the visibility 👀 of our systems. 

## Value
Cloud Operations currently ship all logs to the MLAP, teams have no ability to consume these logs within our [Monitoring Platform](https://github.com/ministryofjustice/staff-infrastructure-monitoring) IMAP.
We do have the ability to use CloudWatch but dealing when dealing with multiple accounts and environments is less than ideal.

## Questions / Assumptions

We should reuse / align with other MoJ areas where possible.
Integration with Grafana and alerting

## Definition of done

- [ ] Analysis of logging options on the market
- [ ] Analysis of logging options within the moj
- [ ] ADR on logging added
- [ ] another team member has reviewed

## Solutions seen elsewhere in MoJ
[Loki](https://grafana.com/oss/loki/) - disk-based index so not memory heavy, integrates with Prometheus when used with Grafana e.g. can match labels. Cloud Platform are investigating see [here](https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/023-Logging.md) 
[CloudWatch](https://aws.amazon.com/cloudwatch/) - low operational overhead but presently difficult to manage multiple across accounts.
[AWS OpenSearch](https://aws.amazon.com/blogs/opensource/introducing-opensearch/) - Managed AWS service based on Elasticsearch.

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/43?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson
