### ISSUE TITLE
List and configure prometheus exporters endpoint

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#430]
List all configured prometheus exporters.
Configure authentication to access proetheus endpoint.

This ticket has been created to carry out work identified from spike on Grafana metrics done in sprint 2nd - 15th August 2023.

**Comment by darey-io** [comment]
To identify dependencies on https://monitoring-alerting.staff.service.justice.gov.uk/metrics we need to have a list of exporters pushing metrics there and configure them to use authentication.

**Comment by jennycasanova** [comment]
Need to discuss with Dare at stand up

**Comment by darey-io** [comment]
After investigation below was discovered

1. The endpoint https://monitoring-alerting.dev.staff.service.justice.gov.uk/metrics is not accessed by prometheus to pull metrics, hence no dependencies are identified to avoid breaking changes
2. Prometheus is pulling the metrics through an internal kubernetes service **kube-prometheus-stack-prometheus**
3. Same thing is observed for thanos-receive.monitoring-alerting.dev.staff.service.justice.gov.uk/metrics
