### ISSUE TITLE
Review the alerting for resource utilisations in DNS cluster

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#434]
**Context:**
This ticket has been spun off from ticket 182 where we encountered DNS errors.
We need to review the alerting for resource utilisations in the cluster so that we are aware of any issues in the future.

**Comment by juddin927** [comment]
concerned raised recently as the DNS cluster was having unhealthy container which created loop of replacing task but not triggered scale up rightly as scale up metric was not hit. configured an alert in grafana to trigger  every time NLB detects an unhealthy container and replaces them.

**Comment by juddin927** [comment]
Also reviewed the cluster scaling config which is currently only using CPU metric to scale up, I suggest we also add memory as a scaling up metric.

**Comment by juddin927** [comment]
- alert: DNS ECS Unhealthy container Alert
      expr: aws_networkelb_un_healthy_host_count_sum{dimension_LoadBalancer=~\".+dns.+\",account_id="{{ .Values.production_account_id }}"} > 0
      for: 5m
      labels:
        severity: critical
        service: DNS DHCP
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: DNS ECS Unhealthy container is above 0
        description: Unhealthy container count is currently {{ "{{ $value }}" }}
        grafana_dashboard_url: https://monitoring-alerting.staff.service.justice.gov.uk/d/tm5gLH1Gz/bind-dns-metrics

**Comment by jennycasanova** [comment]
New ticket to be created to test OOH then this ticket can be closed
