### ISSUE TITLE
SPIKE - Review ATOS files for DHCP rollout

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#439]
We are rolling out MOJ DHCP to the wider MOJ (HMCTS) estate.

ATOS who are the current provider for HMCTS have supplied their files for us to review which includes all the applications etc used on the HMCTS estate.

Time needs to be set aside to review these files.

**Comment by juddin927** [comment]
Global Config breakdown from ATOS

File name: RFI_093_global_config_file


option domain-name "dom1.infra.int";: Specifies the domain name for the DHCP server.

default-lease-time 86400;: Sets the default lease time for DHCP leases to 86,400 seconds (24 hours).
max-lease-time 86400;: Sets the maximum lease time for DHCP leases to 86,400 seconds (24 hours).
log-facility local6;: Specifies the facility to which DHCP log messages will be sent.
authoritative;: Indicates that this DHCP server is authoritative for the local network, meaning it is the official DHCP server.
next-server 10.172.70.23;: Specifies the IP address of the central boot server.
filename "SMSBoot\\X64\\wdsmgfw.efi";: Specifies the filename to be used for network booting.

option option-160 code 160 = string;: Defines a custom DHCP option (Option 160) with a specific code and type.

option option-160 "http://iispac.dom1.infra.int/yealink/";: Sets the value for Option 160, which appears to be a URL.

option option-234 code 234 = string;: Defines another custom DHCP option (Option 234) with a specific code and type.

The include statements are used to include additional configuration files, such as subnet configurations and high-availability (HA) settings.

The comments at the end of the file provide a changelog, documenting changes and updates made to the configuration file over time.



Questions for Global Config

1- what is option-160 code 160 = string; do we need this?
2- option-234 code 234 = string; is this for windows optimisation?
3- Do we need to configure anything for network booting in step 7 as above?

**Comment by juddin927** [comment]
findings on DHCP config file.

https://dsdmoj.atlassian.net/wiki/spaces/LW/pages/4528570553/ATOS+Example+DHCP+Config+File+breakdown
https://dsdmoj.atlassian.net/wiki/spaces/LW/pages/4528570553/ATOS+Example+DHCP+Config+File+breakdown
