### ISSUE TITLE
DNS Capacity Testing 

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#444]
**What**
There is a business wide push to enable PDNS across the estate in order to improve security. Our MoJ DNS service provides this but it is not in use across the entire estate. Currently (exact number tbd) some devices are using Infloblox DNS service. The current tactical solution is to point to the MoJ DNS service in order to provide the PDNS service.

For testing purposes we are looking to double the current amount of traffic for DNS 

This ticket is to complete DNS capacity testing from ticket [376](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/376) 

**Findings From Spike:** 
During this spike, It has been established that dnsperf can be executed from "Corsham Test Bastion" server in AWS.

Here is an output of a test that was conducted

`ubuntu@ip-10-180-82-176:~$ time dnsperf -s staff-device-production-dns-754e69ecf996b619.elb.eu-west-2.amazonaws.com -d test_queryfile -c 1 -Q 10 -t 2 -l 300
DNS Performance Testing Tool
Nominum Version 2.1.1.0.d

[Status] Command line: dnsperf -s staff-device-production-dns-754e69ecf996b619.elb.eu-west-2.amazonaws.com -d test_queryfile -c 1 -Q 10 -t 2 -l 300
[Status] Sending queries (to 10.180.80.5)
[Status] Started at: Tue Jun 27 13:15:17 2023
[Status] Stopping after 300.000000 seconds
[Status] Testing complete (time limit)

Statistics:

Queries sent: 3000
Queries completed: 3000 (100.00%)
Queries lost: 0 (0.00%)

Response codes: NOERROR 2333 (77.77%), NXDOMAIN 667 (22.23%)
Average packet size: request 33, response 117
Run time (s): 300.000323
Queries per second: 9.999989

Average Latency (s): 0.003219 (min 0.000523, max 0.462044)
Latency StdDev (s): 0.021142

real 5m0.140s
user 0m0.057s
sys 0m0.388s`

Lessons learned

Codepipeline did not pick up changes from the code when trying to update the variable to provision a bastion server. This happened because the actual value is supposed to be updated in Parameter store "/staff-device/dns-dhcp/$ENV/enable_bastion" and not in the code.
The generate_tfvars.sh script in the code base is useful only for development environment. It is not optimized for preprod and prod because all the values override are pulled from parameter store at run time.
The Onprem VM is not reachable from the Bastion, hence test was conducted on bastion in AWS. We need to understand more, why it may be necessary to run the tests from the onprem VM
Considerations for Implementation

The bastion server in AWS is configured as a t2.nano instance type. If the testing will be done here, we will need to configure a larger instance
The scope of testing needs to be established. The previous testing that was conducted had 9 tests conducted covering different scenarios. Given the current requirement and load expectations, we will need to be more specific on the desired performance benchmark as this will help us scope the test a lot more better.
Query Load: Desired query load that the DNS server needs to handle. Can we define or articulate what is considered a "heavy load"?
Concurrency: Desired performance under multiple connections
Test Duration: What is the DNS server's stability and performance over an extended period.
Response Time: How quickly do we expect the DNS server to respond. In other words, what is our expectations in terms of DNS server's performance as it relates to latency and responsiveness.
Resource Utilization: What is the maximum resource utilization expected under heavy load.
Scalability and Load Balancing: Do we care about this? Is this part of what we want to see during the tests?
Reporting and Analysis: Do we care about visualizing the test reports for further analysis
With this, we can then proceed with testing.

**Comment by juddin927** [comment]
Conclusions:

1. Add a scaling metric for “Max CPU utilization” (leaving the average in place)
2. Increase CPU capacity from 0.5 to 1 on the ECS clusters (Introduce this change separately to memory)
3. Once it is proven the service can scale correctly, we will then be in a position to set the scaling down config to be able to lower the “desired count”, based on usage. 
4. Reduce memory from 1GB to 512MB  on the ECS cluster. Subject to more testing / validation (Introduce this change separately to CPU)
5. Currently the method of testing cannot generate a high amount of load. Therefore we need to review the method of load testing to increase the amount of queries per second. We can do this by either increasing the amount of hosts running  dnsperf or look into the AWS load testing solution using Jmeter scripts.

**Comment by juddin927** [comment]
detailed of the testing documented below 
https://docs.google.com/document/d/1hEUFC5h4u0K9MQElRQ7AZwx4Iuy3gyIgFQzT7tx7Ez4/edit
