### ISSUE TITLE
Migration to Jira

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#446]

**Comment by bagg3rs** [comment]
@tomwells98 Have you considered [GitHub Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects)

**Comment by tomwells98** [comment]
Tom to have conversation with Sharad and Shreya

**Comment by tomwells98** [comment]
Change freeze could be a good window

**Comment by NNavickas1** [comment]
closing as this has been duplicated
