### ISSUE TITLE
TechOps VPN permissions update

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#453]
What:
We have had a request come through to grant Phil Walker philip.walker@justice.gov.uk permissions to directly modify the variables in the parameter store in  MOJ Official (Shared Services) #683290208331 

This needs urgently needs to be done before there is another VPN scale-out event. 

After this ticket is complete we need to investigate ownership of this repo.

**Comment by smjmoj** [comment]
Contacted Phillip over Slack to establish the details.
They use the "techops-operator" sso role to access the AWS SSM Parameterstore via the AWS Console.
While they can read the paramteres they do not have the "ssm:PutParameter" action.

PR below applied
https://github.com/ministryofjustice/aws-root-account/pull/776/commits/f241eaf209d3990ff155315a6aa38fb08616f337

**Comment by smjmoj** [comment]
Confirmed its working
