### ISSUE TITLE
Additional NAT Gateway for DNS

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#454]
User Story: 
As a DevOps engineer I want to ensure that my services provide as high a level resiliency as possible so that I can reduce the chance of downtime. 

Context:
we need to update our route table and add an additional NAT gateway as the current configuration sites in one availability zone which would mean our service would go down

**Comment by tomwells98** [comment]
Ticket to be updated by Jahir

**Comment by tomwells98** [comment]
we need to update our route table and add an additional NAT gateway as the current configuration sites in one availability zone which would mean our entire service would go down

**Comment by juddin927** [comment]
DNS and DHCP VPC private subnet in AZa and AZb routing traffic via a single NAT(nat-0137946977ae3f9ad).This risk service resilience in the event of an AZ failure. 

Outcome of this ticket would be to update the AZb route table(rtb-0ff36ff3a27ae8756 / staff-device-production-dhcp-dns-private-eu-west-2b
) with NAT in AZb (nat-0b5f7950219dc295d)

**Comment by jamesgreen-moj** [comment]
https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure/pull/295

**Comment by juddin927** [comment]
rolled in the change in DEV and Pre-Prod, we will have to do PROD in a controlled way.

**Comment by juddin927** [comment]
Executing this action in a production environment during regular work hours carries inherent risks. This stems from the necessity to manually delete and re-add the route table, as Terraform currently lacks the capability to update an existing route without the initial manual deletion. Consequently, a brief period of downtime is unavoidable, and it would be prudent to formally initiate a change request for this purpose. The most suitable timing for this would be during off-hours, either late at night or in the evening. Till will place this ticket in BLOCKED status.

**Comment by jamesgreen-moj** [comment]
Production stae modification commands  
```
 terraform state rm 'module.servers_vpc.aws_route.pdns-route-2a-pdns-1["rtb-08908a4069cec43fa"]'
 terraform state rm 'module.servers_vpc.aws_route.pdns-route-2a-pdns-1["rtb-0ff36ff3a27ae8756"]'
 terraform state rm 'module.servers_vpc.aws_route.pdns-route-2a-pdns-2["rtb-08908a4069cec43fa"]'
 terraform state rm 'module.servers_vpc.aws_route.pdns-route-2a-pdns-2["rtb-0ff36ff3a27ae8756"]'`
```

```
IMPORT_ARGUMENT='module.servers_vpc.aws_route.pdns-route-2a-pdns-1["25.25.25.25"] rtb-08908a4069cec43fa_25.25.25.25/32' make import
IMPORT_ARGUMENT='module.servers_vpc.aws_route.pdns-route-2a-pdns-1["25.26.27.28"] rtb-08908a4069cec43fa_25.26.27.28/32' make import

IMPORT_ARGUMENT='module.servers_vpc.aws_route.pdns-route-2b-pdns-1["25.25.25.25"] rtb-0ff36ff3a27ae8756_25.25.25.25/32' make import
IMPORT_ARGUMENT='module.servers_vpc.aws_route.pdns-route-2b-pdns-1["25.26.27.28"] rtb-0ff36ff3a27ae8756_25.26.27.28/32' make import
```

**Comment by jamesgreen-moj** [comment]
Terraform plan for production after successful imports:

Terraform will perform the following actions:

```
  # module.dns.aws_ecs_service.service will be updated in-place
  ~ resource "aws_ecs_service" "service" {
      ~ desired_count                      = 3 -> 5
        id                                 = "arn:aws:ecs:eu-west-2:037161842252:service/staff-device-production-dns-cluster/staff-device-production-dns-service"
        name                               = "staff-device-production-dns-service"
        tags                               = {
            "Name"             = "staff-device-production-dns"
            "Namespace"        = "staff-device"
            "Stage"            = "production"
            "application"      = "dhcp-dns"
            "business-unit"    = "HQ"
            "environment-name" = "production"
            "is-production"    = "true"
            "owner"            = "NVVS DevOps Team: lanwifi-devops@digital.justice.gov.uk"
            "source-code"      = "https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure"
        }
        # (15 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }
```

Plan: 0 to add, 1 to change, 0 to destroy
