### ISSUE TITLE
Add S3 Bucket Versioning to remaining buckets

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#457]
Context: 
This ticket is to add S3 bucket versioning to the remaining repos after Staff-device-dns-dhcp-infrastructure (ticket 87) has been completed. 

This ticket is a stretch goal for the sprint commencing 27/09/2023

User Story: 
As a DevOps Engineer, I want to be able to keep audit history of my Terraform state. This will enable me to compare the differences in the state. All buckets within the shared services account will need to be updated to have versioning enabled.

**Comment by smjmoj** [comment]
Versioning has been applied to 11 S3 buckets managed in 
https://github.com/ministryofjustice/staff-device-shared-services-infrastructure

There is a [review/audit ticket](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/staff-device-shared-services-infrastructure/88) that has been updated with the details.
There are other S3 Buckets that appear to manage Terraform state that we will need to look into where they are created/managed and add the versioning attribute.

**Comment by jamesgreen-moj** [comment]
To be clear, the scope of this ticket is limited to only S3 state file buckets.

There are still some outstanding buckets to add versioning to (not managed in the shared infrastructure repo: https://github.com/ministryofjustice/staff-device-shared-services-infrastructure). These buckets will have state enabled as part of this ticket:  https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/462

As part of this ticket we have configured versioning on all buckets managed by the "https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/462" repo.
