### ISSUE TITLE
Enable versioning on three buckets

### ISSUE THREAD

**Issue by jamesgreen-moj** [ministryofjustice/nvvs-devops#462]
Currently there are three buckets managed by the NVVS DevOps team without versioning on the Terraform state S3 Buckets. These are:

- staff-infrastructure-monitoring-cluster-tf-state (https://github.com/ministryofjustice/nvvs-devops-monitor)
- staff-technology-services-github-teams-core-tf-state (https://github.com/ministryofjustice/staff-technology-services-github-teams)
- mojo-aws-github-oidc-provider-core-tf-state (https://github.com/ministryofjustice/mojo-aws-github-oidc-provider)

These buckets should be updated to enable versioning.

**Comment by smjmoj** [comment]
This bucket (staff-technology-services-github-teams-core-tf-state) is now deprecated and this new IAC managed bucket (staff-ci-technology-services-client-github-teams-tf-state) is being used with the terraform repository staff-[technology-services-github-teams](https://github.com/ministryofjustice/staff-technology-services-github-teams)

Now we need to remove that original bucket

**Comment by smjmoj** [comment]
bucket         = "staff-technology-services-github-teams-core-tf-state"
dynamodb_table = "staff-technology-services-github-teams-core-tf-lock-table"
No longer required have been deleted from the shared-services AWS account.
