### ISSUE TITLE
Site based configuration on Juniper Mist dashboard

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#464]
User Story: 
As a LAN engineer I want to be able to automate the process of uploading sites onto Juniper Mist ahead of the 100 probation sites being added onto the portal so that I can save time. 

Context: 
We have had a request from Matti to pick up work he started that looked to automate adding sites onto the Juniper mist portal. The request is for the ability to fill out a config on a CSV (or maybe google sheets file) and then have the ability to 'wrap' this in JSON so that it can be added to the portal automatically and to save manual time and error. There are going to be an additional 100 probation sites added by March 2024. The LAN engineers would like to have all the config for sites uploaded onto the portal by Christmas ahead of the go live date. 

Juniper Mist links
https://api-class.mist.com/use_cases/site_creation/create_sites/

https://www.juniper.net/documentation/us/en/software/mist/automation-integration/automation-integration.pdf

https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html

[site-creator-inc-site-settings-sle-env-EU-for-MoJ.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTVEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a10d8634857c4e9c0ec368391e65bfb76ec31189/site-creator-inc-site-settings-sle-env-EU-for-MoJ.txt)

Documents supplied in email from Matti
[MoJ-sample-sites (002).xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejFEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8c700143b31fca20630c5c1e8216be3171c5269/MoJ-sample-sites%20%28002%29.xlsx)

[site-creator-inc-site-settings-sle-env-EU-for-MoJ.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejVEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea440f603c4fc9cba3d51980747262e88493f30d/site-creator-inc-site-settings-sle-env-EU-for-MoJ.txt)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGxEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d25bbec7093e4ff4061ece6dc4edb97e75b1844/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejlEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d672fd3426ec48155f2b5a77d494fa059438764d/image.png)

The contact for this ticket is Matti Sysmalainen.

**Comment by tomwells98** [comment]
Need to get the devs access to Juniper Mist dashboard

**Comment by tomwells98** [comment]
Jenny to talk with Matti to refine further

**Comment by jennycasanova** [comment]
Meeting put in for 17.10.23 to clarify the ask of this ticket with Matti.
