### ISSUE TITLE
Log-retention update to 90 days for all environments

### ISSUE THREAD

**Issue by satishgummadellimoj** [ministryofjustice/nvvs-devops#465]
This ticket is from ticket [435](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/435) SPIKE log retention

Also relates to ticket [294](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/staff-device-dns-dhcp-infrastructure/294)

User Story: 
As a DevOps engineer I want to ensure that I have logs that record a sufficient amount of time so that I can record any issues and troubleshoot them. 

**[Link to cost findings** ](https://dsdmoj.atlassian.net/wiki/spaces/MOJO/pages/4541448241/Update+Log+retention+for+Core+services)

**Repos using the Cloudwatch logs**

network-access-control-infrastructure
nvvs-devops-monitor
staff-device-dns-dhcp-infrastructure
staff-device-logging-infrastructure
staff-device-shared-services-infrastructure
staff-infrastructure-network-services

**Comment by jamesgreen-moj** [comment]
I think this should be changed to 90 days, the costs maybe slightly higher but the benefits of being able to analyse further back outweigh the costs.

**Comment by satishgummadellimoj** [comment]
nvvs-devops-monitor-- completed

**Comment by satishgummadellimoj** [comment]
staff-infrastructure-network-services -- completed

**Comment by satishgummadellimoj** [comment]
network-access-control-infrastructure-- completed

**Comment by satishgummadellimoj** [comment]
staff-device-shared-services-infrastructure completed
