### ISSUE TITLE
Spike Tooling Container

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#466]
User Story:
As a DevOps engineer I want to have a tooling container to run workloads. The container will be used to have a consistent experience across the team.

Acceptance Criteria:
The container must be able to run the following tools
1. Terraform
2. kubectl
3. aws cli
4. aws vault
5. helm

To do: 
1.  compare benefits and drawbacks of standard docker container and VSCode Devcontainer
2.  come to a decision of which tool better suits the team 

More requirements:
1. The container must be able to mount to local filesystem to access authentication data such as ~/.aws, ~/.ssh
2. The container must be able to access existing repositories from local PC through mount points
Suggested approach:
1. VSCode devcontainer -- Documentaiton: https://code.visualstudio.com/docs/devcontainers/containers

Having a tooling container where common tools are installed and used by every member of the team.
James recommended a tool that should also be considered for running Github actions locally as part of tooling standardisation --> https://github.com/nektos/act

Useful repo: 
https://github.com/ministryofjustice/hmpps-engineering-tools

**Comment by tomwells98** [comment]
This should be used in the pipeline as well

**Comment by tomwells98** [comment]
2 options, 1. standard docker container and 2. VSCode Devcontainer

**Comment by babatundek** [comment]
Time Box : 2 days

**Comment by smjmoj** [comment]
Container:
https://github.com/ministryofjustice/nvvs-containers

Implementation:
https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure/pull/297

Some usage documentation on both repos to be concluded.
