### ISSUE TITLE
Cloud operations email group

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#468]
User Story:
As an NVVS DevOps team member we should be part of the 
cloud-operations-notifications@justice.gov.uk
email group.

So that:
We are able to fully manage and receive notifications from GitHub regarding the staff-infrastructure-moj service/maching GitHub account.

To do:
add current team
request list of recipients
Housekeep
Include on the onboarding steps

**Comment by smjmoj** [comment]
Touhidul.Islam@justice.gov.uk
requested to be removed.

**Comment by juddin927** [comment]
I have raised a request to add member of devops team(5 members) to the above DL. I noticed there are no option to request member from digital domain group to the justice DL.

**Comment by tomwells98** [comment]
Waiting for Shreya to approve email

**Comment by juddin927** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUdTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef3f6d3aae8a7ba9a6ed568c4472dd374a0ad34a/Screenshot%202023-11-01%20at%2017.36.21.png)

**Comment by juddin927** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1YQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b08cce5a7a3ddd609eb03bc6ec87147ad6e4cfeb/Screenshot%202023-11-02%20at%2011.49.43.png)

**Comment by juddin927** [comment]
tested confirmed working
