### ISSUE TITLE
Increase DNS CPU capacity 

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#473]
Whilst looking at the DNS ECS Service task, usage of CPU on the task is higher than the memory. this ticket is to raise CPU from .5 to 1. in the ECS DNS task cluster. (Introduce this change separately to memory)

Outcome: is. to change the task configuration to upgrade cpu from .5 to 1 in the DNS-DHCP infrastructure repository.
Repo: https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure

**Comment by juddin927** [comment]
Whilst looking at the DNS ECS Service task, usage of CPU on the task is higher than the memory. It could be useful to   raise CPU from .5 to 1. (Introduce this change separately to memory)

**Comment by juddin927** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dab5b19eb451c2bc81ddd3b8baf28a8de7dbc3f1/Screenshot%202023-10-11%20at%2010.55.35.png)

**Comment by juddin927** [comment]
As per the spec this won't be supported by ECS fargate.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-tasks-services.html
May be its better to leave as .5 then raising it to 1 vCPU with 2 GB memory!
