### ISSUE TITLE
NACS documentation 

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#474]
What:
Go through flow logs for previous 7 days. Remove internal MoJ IPS using:
filter     (
        interfaceId="eni-09e3ddb01dc6cb9f9" OR
        interfaceId="eni-0adbdc744511389e2" OR
        interfaceId="eni-08dd10d11811c1675"
    ) OR
    (
        dstAddr="51.149.250.104" OR
        dstAddr="51.149.250.126" OR
        dstAddr="51.149.250.11"
       
    )
| stats count(*) as numHits by srcAddr
| sort numHits desc

send to Thomas Green thomas.green1@justice.gov.uk

**Comment by juddin927** [comment]
Extracted of last seven days for top 100 IPs from VPC flow logs.
https://docs.google.com/spreadsheets/d/1fET-T4qs7t2r1lHKW9G_8FZI30JTrFXfhArvdT7QKQc/edit#gid=0
