### ISSUE TITLE
Daniel The Spaniel Review 🐶

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#478]
Context:
We currently have several outstanding Daniel the Spaniel reviews in the NVVS-DEVOPS channel.
These need to be reviewed and cleared so that they do not continue to generate noise in the team channel.

Steps:

click on the linked pages
review the content
Add any needed changes
update review date

**Comment by smjmoj** [comment]
Updated three pages reported by Daniel on Slack
https://github.com/ministryofjustice/nvvs-devops/compare/daniel-manual-spaniel?expand=1
