### ISSUE TITLE
🧪SPIKE DHCP Pagination

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#490]
User Story:
As a LAN engineer I want to be able to easily navigate through the DNS/DHCP portal regardless of how many sites are uploaded onto it. So that I am not impaired by adding more sites onto MoJ DNS. 

Context:
We need to ensure that the DNS/DHCP portals usability is not reduced by adding sites onto it. Currently we only display sites on 1 page. We need to add pagination as when more sites get added only displaying it on one page will cause difficulty for users to navigate and potentially performance issues. 

To Do

- [ ] We have pagination on the NACS portal. Can any of this be reused? 
- [ ] explore different options and any potential complications for adding pagination onto the DNS/DHCP portal
- [ ] Attach findings to this ticket

**Comment by NNavickas1** [comment]
https://dsdmoj.atlassian.net/jira/software/c/projects/ND/boards/1430/backlog?epics=visible&selectedIssue=ND-44&text=pagi
