### ISSUE TITLE
🧪SPIKE Review Critical CVE findings from AWS Inspector on Lambda and action as appropriate

### ISSUE THREAD

**Issue by jamesgreen-moj** [ministryofjustice/nvvs-devops#495]
Reviewing AWS inspector, I can see a total of 20 critical findings on our lambdas. These critical findings need to be reviewed and patched.

https://eu-west-2.console.aws.amazon.com/inspector/v2/home?region=eu-west-2#/findings/all

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzExQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8257b34bdcc80a25e52462325b3441f11b826494/image.png)

**Comment by tomwells98** [comment]
ECR ticket to be looked at first
