### ISSUE TITLE
NAC Open SSL version 3 Upgrade release to Production

### ISSUE THREAD

**Issue by babatundek** [ministryofjustice/nvvs-devops#497]
A follow up for ticket #168. 
The aim of this ticket is to release the alpine and Openssl version upgrade released in to the production environment

Change is planned: https://mojprod.service-now.com/now/nav/ui/classic/params/target/change_request.do%3Fsys_id%3Dba7df4a91b3fb914de03620be54bcbae%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull%26sysparm_view%3D
Start: 25-01-2024 17:00:00
End: 25-01-2024 19:00:00

Prerequisites - 
- Tests are completed by LAN
- Tests are successful 

Outcome:
- Change in #[168](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/network-access-control-server/168) is released in to production.

To Do: 

- [ ] Rollback plan 
- [ ] Release into production
- [ ] LAN resources need to be available for production testing

**Comment by tomwells98** [comment]
Ticket is for tracking on the LAN side. When the tests are completed by them we can pick this ticket up and release in production

**Comment by babatundek** [comment]
to be released on the 25th. CR has been approved
