### ISSUE TITLE
Create a checklist to qualify dependebots

### ISSUE THREAD

**Issue by babatundek** [ministryofjustice/nvvs-devops#501]

**Comment by smjmoj** [comment]
Initial spreadsheet created here:
https://docs.google.com/spreadsheets/d/1VrP9lcakz9U5mcskmRVAEXf6pbus70A7KVKlQZh6gXI/edit?usp=sharing

**Comment by smjmoj** [comment]
People can edit and view it.
I have done a quick review and made some quick judgements. They need to be reassessed.

Also a repo with no Dependabot or Renovate PRs may indicate this has not been configured on the repo and should have that added.

**Comment by smjmoj** [comment]
I've done a quick review of the Repos and updated the spreadsheet.

I would like it if somebody else checked and agrees with my assessment (it was quick and most likely not always correct).

Also it was boring :disappointed:
So I suggest we do this as a team so we divide the work by 5 .
And perhaps each morning as PRs are pushed into the "in progress" column we assess each one and update the spreadsheet. 
This way we can see anything that could be urgent and schedule accordingly.
