### ISSUE TITLE
🧪SPIKE Upgrade from MySQL v5 RDS v8

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#502]
Context:

MySQL community plans to deprecate MySQL 5.7 in October 2023 and it will not receive any security patches after October 2023. Therefore, Amazon RDS will end standard support of MySQL major version 5.7 on February 29, 2024.

alert we received:
'You are receiving this notification because you have one or more Amazon RDS for MySQL database instances running on db.m4, db.r4, or db.t2 instance types. We plan to retire all M4, R4, and T2 instances by April 2024. We recommend that you upgrade all your db.m4, db.r4, or db.t2 instance types prior to their retirement. Reserved instances for db.m4, db.r4, and db.t2 will no longer be available for purchase beginning on June 30, 2023.'

There are four databases to go through which are linked below:

https://docs.google.com/spreadsheets/d/1LjlRDQVHYk8avpZkdkP9ArksvhFufKcI9wfsGdTDlnI/edit#gid=0 

This needs to be done before RDS end of standard support in February 2024.

To Do: 

- [ ] Check we are responsible for these DBs
- [ ] review each DB 
- [ ] define scope and create a ticket for each 4 DB 
- [ ] upgrade from GP2 to GP3

**Comment by NNavickas1** [comment]
closing as this is a duplicate
