### ISSUE TITLE
Github Group Add Users

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#503]
What: 
We received a request in the NVVS DevOps channel to add news users to a Github repo from Gullbhar Majid. The requested users are:
Dana-Crawford, CharlotteBMoJ, T1m2k2, EmmaSandman, JohnLillingtonMOJ, Jamie-Huntington

Repo requested for access: 
https://github.com/ministryofjustice/staff-external-dynamic-list

We should look into reducing the scope for access. Perhaps create another team / group to put people into .
Also we need to review the group the existing contributors to the staff list repo are in.

- [x] Dana-Crawford
- [x] CharlotteBMoJ
- [x] T1m2k2
- [x] EmmaSandman
- [x] JohnLillingtonMOJ
- [ ] Jamie-Huntington

**Comment by smjmoj** [comment]
Jamie-Huntington isn't a member of the MOJ GitHub Org.
He will need his line manager to request access to join the Org prior to being added to the team which can manage the repo.

**Comment by smjmoj** [comment]
Done

**Comment by smjmoj** [comment]
Gullbhar notified via Slack
https://mojdt.slack.com/archives/C01J2L0SC0P/p1699872191920159?thread_ts=1697549214.827939&cid=C01J2L0SC0P
