### ISSUE TITLE
Review alert in mojo-ima-platform-alerts-dev-preprod

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#523]
We are seeing a reoccurring alert in mojo-ima-platform-alerts-dev-preprod

We need to review this alert as it is creating a lot of noise

**Comment by juddin927** [comment]
alerts are being generated from following node 
10.180.100.31
10.180.101.83
These are production nodes in EKS cluster although the alarms are coming up in dev/pre-prod slack channel. Being generated everyday mostly in the morning after 11:00

**Comment by juddin927** [comment]
Unable to locate the configuration of these alarm, only place I can trace this slack channel is in the primary alert manager.
 receivers:
    - name: Master Route
      slackConfigs:
        - apiURL:
            key: ima_slack_webhook_url
            name: slack-webhooks
            optional: false
          channel: '#mojo-ima-platform-alerts-dev-preprod'
          sendResolved: true
          title: {{`'{{ template "slack.alerts.title" . }}'`}}
          text: {{`'{{ template "slack.alerts.text" . }}'`}}
          username: {{`'{{ template "slack.alerts.username" . }}'`}}
          color: {{`'{{ template "slack.alerts.color" . }}'`}}
          iconEmoji: {{`'{{ template "slack.alerts.icon_emoji" . }}'`}}
    - name: NVVS DevOps

**Comment by juddin927** [comment]
After further investigation it was evident that the load per CPU metric for kube-prometheous metric were not being reset over time and that was causing the alarm to trigger. Cluster node have been redeployed and this has cleared alarm threshold.<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzR0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3fb095bed2edd90eb97fa012a71ba48c8bedf834/Screenshot%202023-12-04%20at%2018.33.33.png" alt="Screenshot 2023-12-04 at 18.33.33.png" />

**Comment by juddin927** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGN0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc9dfbda04057205439482b93c5a4a5b614213c0/Screenshot%202023-12-04%20at%2018.38.58.png" alt="Screenshot 2023-12-04 at 18.38.58.png" />
