### ISSUE TITLE
Release DHCP search function in Dev and Pre-prod

### ISSUE THREAD

**Issue by juddin927** [ministryofjustice/nvvs-devops#525]
This is related to search feature on DHCP ADMIN console. This ticket is  to release the feature in to Development and Pro-Production environment.  

https://github.com/ministryofjustice/nvvs-devops/issues/409

**Outcome **
- Release the Changes in to development and Pre-Production  
- Complete UAT by LAN

**Comment by tomwells98** [comment]
Ticket for UAT on LAN side https://dsdmoj.atlassian.net/browse/SR102-862
