### ISSUE TITLE
Route 53 Assessment Support

### ISSUE THREAD

**Issue by NNavickas1** [ministryofjustice/nvvs-devops#528]
**As a** Business Analyst
**I want to** assess the suitability of Route 53 to replace BIND by answering these questions
1. How our DNS infrastructure was built ?
2. Have we made any changes to the architecture since documents were update (Jan 2021)
2. What features of Route 53 we already use? Which ones might be useful in future?
3. Are there any features used in BIND that we don't have for Route 53?
4. What are the costs now?
5. How will the costs change when scaled? 
6. What are the expected needs for scaling and cost in future?
7. What is the effort and risks of running the service ourselves?

TIME BOXED FOR 1 DAY MAX

**So that** I can put together a business case for using Route 53 as our DNS service.

**Description**:
Senior leadership have questions surrounding compatibility of Route 53 for our DNS requirements, since there are already 5 zones hosted in Route 53. The request is to assess whether we can use Route 53 and whether there will be any greater or lesser risk for doing so.

Useful contacts:
Matt White

https://dsdmoj.atlassian.net/wiki/spaces/MOJO/pages/2320990455/DHCP+and+DNS+Services

![image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjc2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1fa9b13752cefb8a61479d47c3c9db59f4e3649/AWS%20Architecture.png)

**Comment by smjmoj** [comment]
Document:
https://docs.google.com/document/d/1MUbpW_m7s-V1qUDZW7zu2Sfbuznh-g2ojoHQ8BB9NGg/edit
