### ISSUE TITLE
Lost access to NAC's Dev and Pre-prod

### ISSUE THREAD

**Issue by juddin927** [ministryofjustice/nvvs-devops#530]
We need to agree the formal process to request access to dev and pre prod
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d2eac352b9e5307dcfabe2d68362691ed5a7e58/Screenshot%202023-11-21%20at%2010.12.23.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0lCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89fafb83e84699ec0f7a652cf17c44fd029753ec/Screenshot%202023-11-21%20at%2013.42.14.png)

**Comment by juddin927** [comment]
moj-development-network-access-control-admin-azure-app
Sorry, but we’re having trouble with signing you in.

AADSTS50105: Your administrator has configured the application moj-development-network-access-control-admin-azure-app ('8f5969df-cce5-4d78-ab28-3c97dd912225') to block users unless they are specifically granted ('assigned') access to the application. The signed in user 'juddin-admin@devl.justice.gov.uk' is blocked because they are not a direct member of a group with access, nor had access directly assigned by an administrator. Please contact your administrator to assign access to this application.

**Comment by juddin927** [comment]
Ideally we should be able to access using jahir.uddin@justice.gov.uk

**Comment by tomwells98** [comment]
Hi Stephen, if you can send an email to the Product lead - Nitesh.Thakur@justice.gov.uk. He should be able to let you know. Call to be scheduled to for Jahir and James (likely Dare as well)

**Comment by NNavickas1** [comment]
Request for more info from Jacob Khoo 21/12/2023
<img width="827" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkNDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e72394cf7e23f5c4c261beb0d7b7f6be90abfd43/image.png" alt="image.png" />

**Comment by NNavickas1** [comment]
imran.aslam4@justice.gov.uk supporting with certificate renewals, but seeking authority to create new certificates. Unable to identify N-Kidd or A-Mitchell.

**Comment by NNavickas1** [comment]
This [:thread:](https://mojdt.slack.com/archives/C04MN9N2ZKN/p1704369662494959) gives details on who the previous notified persons were. 
These are being changed to DevOps - Stephen, James & Jahir.
New certificates to be created by Azure Team (Imran Aslam), and then uploaded server side by DevOps - TBC.

**Comment by NNavickas1** [comment]
Making no progress with current discussions - exploring other avenues to resolve. We now need access for James and at least one LAN engineer to perform acceptance testing

**Comment by NNavickas1** [comment]
Danial Mahmood seeking support from IDAM on our behalf

**Comment by NNavickas1** [comment]
IDAM have confirmed the correct process is via them - they asked us to raise a SNOW ticket, but they don't have a specific form. Natalie to write a short doc to this effect on confluence, and clarify which form to use in future. Imran is working on access for all 4 users

**Comment by NNavickas1** [comment]
Accounts provided to James and Sandhya - users to check that they have the correct privileges
