### ISSUE TITLE
🧪SPIKE - Tracking pinned versions & ensure alerts

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#536]
What:
This ticket is in relation to ticket [218 [Docker containers not pinned to versions]](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops-monitor/218)

After pinning versions to avoid any breaking changes we need to make sure we are correctly monitoring and alerting. Potentially we could use dependabot for this.

Ticket to be revisited after pinning versions. 

Time box: 2 days

**Comment by NNavickas1** [comment]
Can this be covered between dependabot & renovate? (dependabot preferred for github integration)

**Comment by jamesgreen-moj** [comment]
Tracking pinned versions in nvvs-devops-monitor after this is implemented.
