### ISSUE TITLE
🧪SPIKE Log Retention Review

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#539]
This ticket is to review the work in ticket [465](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/465)

We have discovered that not all repos have been upgraded to 90 days for logs. We need to go through and review the logging on our repos and upgrade any that are not currently set to 90 days. 

Repos that need to be added
-  mojo-production-nac-server-log-group

**Comment by juddin927** [comment]
List of CloudWatch log group with retention set as 1 week. https://docs.google.com/spreadsheets/d/1DyvlHSRX_AMZdA-HFNx1_LFWGcb2D9OQ_Fdw61ycEGI/edit#gid=1455592174

**Comment by juddin927** [comment]
Final List 
/aws/rds/instance/mojo-production-nac-admin-db/error	7	Yes
/aws/rds/instance/mojo-production-nac-admin-read-replica/audit	7	Yes
/aws/rds/instance/mojo-production-nac-admin-read-replica/error	7	Yes
/aws/rds/instance/mojo-production-nac-admin/audit	7	Yes
/aws/rds/instance/mojo-production-nac-admin/error	7	Yes
/aws/rds/instance/mojo-production-nac-db/error	7	Yes
/aws/rds/instance/staff-device-production-dhcp-admin-db/audit	7	Yes
/aws/rds/instance/staff-device-production-dhcp-admin-db/error	7	Yes
/aws/rds/instance/staff-device-production-dhcp-admin-db/slowquery	7	Yes
/aws/rds/instance/staff-device-production-dhcp-db/audit	7	Yes
/aws/rds/instance/staff-device-production-dhcp-db/error	7	Yes
/aws/rds/instance/staff-device-production-dhcp-db/slowquery	7	Yes
mojo-production-nac-admin	7	Yes
mojo-production-nac-admin-vpc-flow-logs-vpc-flow-logs-log-group	7	Yes
mojo-production-nac-server-log-group	7	Yes
mojo-production-nac-server-nginx-log-group	7	Yes
mojo-production-nac-vpc-flow-logs-log-group	7	Yes
staff-device-production-infra-cloudtrail-log-group	7	Yes
staff-device-production-infra-vpc-flow-logs-log-group	7	Yes
staff-infrastructure-production-network-services-vpc-flow-log-group	7	Yes
staff-infrastructure-production-smtp-relay-server-log-group	7	Yes
staff-infrastructure-production-smtp-relay-server-nginx-log-group	7	Yes
staff-infrastructure-production-smtp-relay-server-postfix-exporter-log-group	7	Yes

**Comment by juddin927** [comment]
[Ticket Raised](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/545) to update above log group
