### ISSUE TITLE
🧪SPIKE : Deploy Kubernetes resources using GitOps through ArgoCD approach rather than the deploy.sh shell script

### ISSUE THREAD

**Issue by darey-io** [ministryofjustice/nvvs-devops#542]
Following a conversation that was shared on slack here https://mojdt.slack.com/archives/C04MN9N2ZKN/p1701181521120869

There is the need to review the shell script that does the entire deployment of the monitoring stack, and the release strategy that has been adopted.

Some of the issues identified are:

1. Dev, Preprod and prod configuration are muddled up together in the same place
2. Versioning of helm deployments and configuration does not exist
3. Manual rollback of releases using another uninstall.sh shell script which is prone to unintended problems
4. Visibility into infrastructure changes with proper auditing is limited
5. Declarative configuration should be encouraged as much as possible, shell scripts are difficult to maintain

This ticket is to discuss the possibilities of using a GitOps model which addresses all of the above concerns.

**Comment by smjmoj** [comment]
More detail in this closed ticket
https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops-monitor/227
