### ISSUE TITLE
Juniper Mist Dockerization 

### ISSUE THREAD

**Issue by jamesgreen-moj** [ministryofjustice/nvvs-devops#548]
As a DevOps engineer, I want to be able to run this script with 100% confidence. By building it in docker, we can run this within the team with a high degree of confidence it will work. 

DOD:
Docker build local (package the script)
Docker run (Run the script)
Docker run unit tests (Run the unit tests)
Docker IDE integration

**Comment by smjmoj** [comment]
PR for this work
https://github.com/ministryofjustice/juniper-mist-integration/pull/6

**Comment by smjmoj** [comment]
related to parent ticket
https://github.com/ministryofjustice/juniper-mist-integration-spike/issues/4

**Comment by smjmoj** [comment]
https://github.com/ministryofjustice/juniper-mist-integration/pull/6/files
