### ISSUE TITLE
Juniper mist Configuration options

### ISSUE THREAD

**Issue by jamesgreen-moj** [ministryofjustice/nvvs-devops#551]
In the initial scope, it was understood that these values where fixed: RF_TEMPLATE_ID, SITE_GROUP_IDS, ORG_ID

and Enable GovWifi,Enable MoJWifi should be stored as custom_vars on the mist console.

These understanding where incorrect.

Values RF_TEMPLATE_ID, SITE_GROUP_IDS, ORG_ID are dynamic depending on what environment you are running on.

 Enable GovWifi,Enable MoJWifi should be stored within "site_groups" within the mist console AND SITE_GROUP_IDS are required to be defined so that when a field gets read in as TRUE or FALSE from the spreadsheet, it can assign the site to the correct site_group_id. 

DOD:
1. Add support for to allow user to inject vars: RF_TEMPLATE_ID, SITE_GROUP_IDS, ORG_ID
2. Add input validation
3. Update docs
3. Update unit tests

**Comment by smjmoj** [comment]
related to https://github.com/ministryofjustice/juniper-mist-integration-spike/issues/4
