### ISSUE TITLE
NACS critical alert 13/12/2023

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#554]
This ticket is linked to ticket [#527](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/527). 

The same alarm reoccurred. However this alert was alert was not a false positive. 

It looks like the error occurred after MAC address bypass was updated on the NACS portal at 15:46, causing the service to redeploy.

We need to further investigate the error logs and continue to contact AWS for further information.

Link to the slack alert: https://mojdt.slack.com/archives/C01J2L0SC0P/p1702486292312709?thread_ts=1702482931.883029&cid=C01J2L0SC0P

**Comment by juddin927** [comment]
further ticket on this 
https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops-monitor/225
