### ISSUE TITLE
DNS Record required for HMCTS Database access(Global Protect DOM1 Laptop PILOT (URGENT)

### ISSUE THREAD

**Issue by juddin927** [ministryofjustice/nvvs-devops#560]
DNS Forwarders to be set up on the MOJO DNS Service:

 

Forward:

ss01-sqlsrv-stg.database.windows.net

ss02-sqlsrv-stg.database.windows.net

ss01-sqlsrv-prod.database.windows.net

ss02-sqlsrv-prod.database.windows.net

to the HMCTS DNS Server:

10.24.0.53

 

 

Forward:

glb.ctsc.hmcts.net

antenna.no10.gov.uk

civilappeals.local

to the ATOS DNS Servers:

10.171.68.147

10.171.68.148

10.171.68.149

10.171.68.150

10.172.68.147

10.172.68.148

10.172.68.150

**Comment by juddin927** [comment]
I discovered that there are valid public DNS resolution for the specified domain. I am concerned that this could inadvertently disrupt certain services within the Ministry of Justice's DNS infrastructure if they are dependent on the public DNS for the given namespace.

**Comment by juddin927** [comment]
Change implemented on Friday

**Comment by juddin927** [comment]
Agreed a way forward this will be implemented with a new change as the scope significantly changed

**Comment by NNavickas1** [comment]
Due to the increase in scope [#578](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/578) has been raised to complete the change request
