### ISSUE TITLE
DNS add zones - make this a standard change

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#567]
We need to look into making it a standard change for adding DNS zones on MoJ DNS. The change request process has been followed 3 times, so can now be applied as a standard change.

Talk to Mika in LAN/Wifi and Lynne Walton to progress this 

Change [STDCHG0002655](https://mojprod.service-now.com/now/nav/ui/classic/params/target/std_change_proposal.do%3Fsys_id%3D754d569d1b4046d00c7d646fe54bcb07%26sysparm_stack%3Dstd_change_proposal_list.do%3Fsysparm_query%3Dactive%3Dtrue) submitted

**Comment by NNavickas1** [comment]
[KBA](https://mojprod.service-now.com/now/nav/ui/classic/params/target/kb_view.do%3Fsysparm_article%3DKB0020459)

**Comment by NNavickas1** [comment]
This cannot be completed yet, as the 3 changes previously completed were not all 100
% successful. We will need a 3rd successful change before we can implement the standard change

**Comment by NNavickas1** [comment]
on jira
