### ISSUE TITLE
Juniper make firmware version configurable 

### ISSUE THREAD

**Issue by jamesgreen-moj** [ministryofjustice/nvvs-devops#568]
Currently the firmware version of the APs are hard coded, this means every time they change it requires an update to the code base. 

E.G: https://github.com/ministryofjustice/juniper-mist-integration/pull/12/files

This needs to change so it is configurable by the env file instead. 

This will allow LAN to update the AP's without having to come to DevOps

DOD:

- Update the example docker .env file with new input value: `AP_VERSIONS={"AP45": "0.12.27139", "AP32": "0.12.27139"}`
This should be inputted as a Python dict, this gives the ability for new APs to be added in future. Matti has confirmed that versions could differ per AP.
- Add in new environment var `AP_VERSIONS` for  within the Python script.
- Ensure input validation is updated in python script. https://github.com/ministryofjustice/juniper-mist-integration/blob/cf59efcffb9bd1c93a6a519c9bcea750728fc720/src/juniper.py#L339
- Make sure unit tests reflect changes and run correctly.\
- Run test code coverage and make sure we are above 85%
- PR (Wait for approval)
- Merge 
- Release new version:
```
git checkout main
git pull
make tag SEMVAR=major 
```
(This is a major change, because we will not support backward compatibility with the old env file.)

**Comment by darey-io** [comment]
PR for change https://github.com/ministryofjustice/juniper-mist-integration/pull/18

**Comment by sb21460** [comment]
Tests ran successfully

**Comment by darey-io** [comment]
More work still required in the Unit Testing part of the code. 

Getting errors with juniper_script function

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/mock.py", line 1375, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/test/test_juniper.py", line 125, in test_given_mist_login_method_not_defined_then_default_to_credentials
    juniper_script([],
  File "/app/src/juniper.py", line 371, in juniper_script
    raise ValueError('Must provide a valid dictionary for ap_versions')
ValueError: Must provide a valid dictionary for ap_versions

======================================================================
ERROR: test_juniper_script (test.test_juniper.TestJuniperScript.test_juniper_script)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/mock.py", line 1375, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestJuniperScript.test_juniper_script() missing 1 required positional argument: 'ap_versions'`

**Comment by sb21460** [comment]
Fixed the errors. 
Test ran <img width="1595" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f16930369b0d93a19a3fc16366161636d4f94fc/Screenshot%202024-01-30%20at%2014.11.39.png" alt="Screenshot 2024-01-30 at 14.11.39.png" />
successfully.
