### ISSUE TITLE
Update Disaster Recovery Page

### ISSUE THREAD

**Issue by NNavickas1** [ministryofjustice/nvvs-devops#572]
[Disaster recovery](https://ministryofjustice.github.io/nvvs-devops/runbooks/disaster-recovery.html#disaster-recovery) age is out of date and requires review.

DOD:
- [ ] Page reviewed and updated to reflect current processes
- [ ] Review date set to the future and warning box no longer present

**Comment by smjmoj** [comment]
I think this needs scoping as separate tickets to test and confirm; as it mentions three separate products which none of the current team members had been involved in the creation of the recovery documents/procedures.

Unless that is done in this case this document can't be confirmed with any confidence.
