### ISSUE TITLE
IP address audit trail JIRA

### ISSUE THREAD

**Issue by jamesgreen-moj** [ministryofjustice/nvvs-devops#574]
Investigate enabling IPAM to give us IP address audibility on IP address history.

https://eu-west-2.console.aws.amazon.com/ipam/home?region=eu-west-2#Dashboard

As a DevOps Engineer when a network engineer provides me with an IP that is not currently in use within the AWS account. I want the ability to lookup what it was used for. enabling this feature should give me that functionality.

On inspection its already enabled in Dev, (Likely to be click ops). We need to refine this ticket:

Should this be Terraformed? If so what repo? This is an account configuration not related to a specific service.

**Comment by smjmoj** [comment]
Turn on in our accounts
Shared, Pre-production, Production and any other accounts we manage eg PKI

Document on Confluence.
