### ISSUE TITLE
Kinesis Firehose Implementation NACS

### ISSUE THREAD

**Issue by NNavickas1** [ministryofjustice/nvvs-devops#576]
Placeholder ticket for the work required to support MIP with onboarding NACS to XSIAM using Kinesis Firehose

Tasks/Deliverables 

- [x]  Create a kinesis data firehose(with source DIRECT PUT, Destination HTTP endpoint) 
- [x]  Create kinesis role with access to S3 bucket 
- [x]  Configure existing Cloud watch log group(NACS server log group) subscription to Kinesis data firehose 
- [x]  This should be configured for all 3 environments (production,pre-production and development)
- [x]  Credentials(accesskeys and URL) for destination HTTP endpoint from XSIAM for NACS server log group.Also need buffer size(if any) and retry duration and content encoding(if required)

Stakeholder:
Stuart Taylor
Thomas Green

**Comment by juddin927** [comment]
buffer size 5MiB and buffer period 300 seconds and retry in 300 seconds--Provided by Touhid

**Comment by smjmoj** [comment]
Discussion with Touhid, he has some example Terraform code which he can provide via a ZIP or Tar file.

**Comment by juddin927** [comment]
This has been deployed in DEV and Preproduction to test data ingestion in to XSIAM once tested will release in to Production
