### ISSUE TITLE
Upgrade mySQL on DNS/DHCP

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#585]
Auto-enrolled to RDS Extended Support on February 29

Conduct local testing; if any application level changes are required, then re-estimate this ticket

Costs will go up from the end of February 
This needs to be carried out before August. 

Potential for end of April or March to carry this out

Your PostgreSQL 11 and MySQL 5.7 databases will be automatically enrolled into RDS Extended Support on February 29, 2024. To avoid the increase in charges due to RDS Extended Support, we recommend upgrading your databases to a newer major engine version before February 29, 2024. To learn more about the RDS Extended Support pricing, refer to the pricing page.

Downtime
Downtime isn't required to apply this recommendation.

https://eu-west-2.console.aws.amazon.com/rds/home?region=eu-west-2#recommendation:recommendationId=7a6fed09-adf5-4932-b508-e3145c57f1b5

DOD: 

Starting DNS/DHCP update both databases:

- [x] Update SQL version locally to 8.*
- [ ] Test and validate changes locally
- [ ] Make Terraform changes for both databases
- [ ] Apply to Test environment, Test and PR
- [ ] Apply to pre-production and production

**Comment by smjmoj** [comment]
Updated to MySQL version 8.0.35 locally ([the newest version supported by AWS in RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.Concepts.VersionMgmt.html).
Tests passed.
