### ISSUE TITLE
Instance type Upgrade

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#586]
Will start with DNS/DHCP infrastructure then follow up with other repos, once we have completed this ticket:
https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure

X2 DB in this repo:
DHCP Admin & DHCP Server

DoD:
- [ ] Check the backups to ensure recent copy exists
- [ ] Update the Terraform to change database instance class (db.t3.medium)
- [ ] Run a Plan & run against Development  
- [ ] PR Review
- [ ] Deploy to pre-production the production

https://repost.aws/articles/AR_Rw2Xbe5Q9O1ZPKbU5S4Mg/amazon-rds-for-sql-server-is-ending-support-for-m4-r4-and-t2-database-instances-on-march-29-2024

**Comment by NNavickas1** [comment]
added to Jira https://dsdmoj.atlassian.net/browse/ND-123
