### ISSUE TITLE
🧪SPIKE uniformity across containers 

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#590]
What: We do not currently have identical container images across testing and production. This could cause unknown issues between test and prod. e.g. a newer version of a library could be pulled down. 

We want the containers promoted per environment rather than built per environment. 

We need to look into building this on GitHub actions. 

DoD:
- [ ] Reuse reusable workflows where possible
- [ ] move existing code onto GitHub actions off of CodeBuilder  
- [ ] Rebuild pipeline to 
- [ ] James to update this ticket with previous related work
- [ ] Look into a centralised ECR repository design 
- [ ] Feedback findings to team about best way to approach this task  
- [ ] Do the below suggestion improve our current configuration
- [ ] 

Timebox: 
2 days 

Useful Contact:
James Green (implemented pic 1 on a prior occasion) although option 2 or 3 may be better for managing the logic

**Comment by jamesgreen-moj** [comment]
<img width="588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3phQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b3205a8bdb02e1023a362a69e3efea112ab7d69/image.png" alt="image.png" />

**Comment by jamesgreen-moj** [comment]
<img width="948" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXZoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d70cce836c308635afb7555731eab60f58b2a8ff/Process%20for%20container%20management-Desgin%202.drawio.png" alt="Process for container management-Desgin 2.drawio.png" />

**Comment by jamesgreen-moj** [comment]
<img width="808" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXpoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0640df9aecc564c530feca39e099c7c5941519a7/Process%20for%20container%20management-Design%203.drawio.png" alt="Process for container management-Design 3.drawio.png" />

**Comment by NNavickas1** [comment]
https://dsdmoj.atlassian.net/jira/software/c/projects/ND/boards/1430/backlog?epics=visible&selectedIssue=ND-84
