### ISSUE TITLE
Unhealthy hosts during incident

### ISSUE THREAD

**Issue by NNavickas1** [ministryofjustice/nvvs-devops#593]
What: 

Ticket is open as Jahir is in talks with AWS regarding this issue.
We need to understand what caused the health checks to fail during the incident between 2:54 and 2:58. Call to be scheduled with AWS to understand this further. 

We do not have the visibility of the health check logs.

**Comment by juddin927** [comment]
Reviewed the update from AWS, Raised further queries with them.

**Comment by NNavickas1** [comment]
opened on Jira
