### ISSUE TITLE
SPIKE Load balancer resiliency

### ISSUE THREAD

**Issue by NNavickas1** [ministryofjustice/nvvs-devops#594]
As a devops engineer
I want to investigate the need for a more resilient set up with AWS load balancers
So that I can implement more resilient zoning if required

Look into utilising 3 AZ's

**Comment by tomwells98** [comment]
Natalie to speak with Shreya to confirm requirements for this ticket

**Comment by NNavickas1** [comment]
HLD updates required, and ADR?

**Comment by NNavickas1** [comment]
Tom Churnside directed us to Ian - to discuss R53 and loadbalancing concerns

**Comment by NNavickas1** [comment]
on jira
