### ISSUE TITLE
Dependabot 17/01/2024

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#603]
https://github.com/ministryofjustice/staff-infrastructure-network-services/pull

**Comment by darey-io** [comment]
Merged - https://github.com/ministryofjustice/staff-infrastructure-network-services/pull/142

**Comment by darey-io** [comment]
Merged: https://github.com/ministryofjustice/staff-infrastructure-network-services/pull/138

**Comment by darey-io** [comment]
Merged: https://github.com/ministryofjustice/staff-infrastructure-network-services/pull/138

**Comment by darey-io** [comment]
All terraform related dependabots have been addressed
