### ISSUE TITLE
🧪Spike What do we have to do to enable CRL for NACS (for DHL)

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#605]
User Story: 
As a network engineer I want to ensure that devices are using .1x authentication to improve security and network functions. 

High level questions:
What is it going to take to do this 
What is it going to cost to do this - resource, additional infrastructure
What are the risks of doing this 

Context:
For the PRS project we nee to look into enabling CRL authentication for DHL as OCSP cannot be used.

DoD: 
- [x] Create test cases to run against service 
- [x] Understand the technical possibility of enabling CRL
- [x] Understand the cost of implementing this change 
- [x] Any impacts to the current service 
- [x] Any potential risks to the current service 

Useful Contacts: 
Matti

**Comment by smjmoj** [comment]
Have local development envs ready - tests passed [with this change](https://github.com/ministryofjustice/network-access-control-server/compare/main...606_Spike_to_enable_CRL_for_NACS#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R8) to the server configuration for OpenSSL

Demoed to James who also has the testing set up working locally.

**Comment by jamesgreen-moj** [comment]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/assembly_setting-up-an-802-1x-network-authentication-service-for-lan-clients-using-hostapd-with-freeradius-backend_configuring-and-managing-networking

**Comment by smjmoj** [comment]
In response to the three last items:

1. Understand the cost of implementing this change
2.  Any impacts to the current service
3.  Any potential risks to the current service

1: It would be difficult to estimate any additional costs. However as it's configuration there should be negligible costs involved if any at all.

2 & 3 Are very similar; from the testing we've done which appears to work fine in the scenarios we have we can not come to any conclusion to say whether it would or would not have any adverse effect.
We would need to do some testing in DEV by or with help from the Lan team with some real devices; using the certs as presented by the organisation.
Currently it looks like the CA cert doesn't specify any CRL or OCSP details for the client device to check against, therefore it isn't clear if enabling CRL would work for the new CA or have an adverse effect on the existing devices/clients that already work with the system as designed and configured.
