### ISSUE TITLE
DHCP Timeouts 

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#628]
What: 
Following investigations from the LAN it appears that there have been 11 DHCP containers active for the last 7 days. Only 1 of these containers is reported as successfully issuing DHCP during this time period 10.180.80.174. All others show nothing but timeouts and errors. 

We need to investigate this issue further to help identify the root cause of the DHCP timeouts at probation sites. 

Info from LAN:
As an engineer

I need to investigate why there are DHCP timeout events occurring on every or most of the Probation Mist sites which are using MOJ DHCP

so that this issue can be rectified prior to the commencement of the deployment of MOJ DHCP rollout to all of our estate

It is considered that this timeout is most likely not client affecting as the sites that already have MOJ DHCP have been in this state since deployment and the issue has not been raised from the end user.  However there is clearly an issue somewhere and this does need to be investigated and resolved.

Useful Contact: 
Mark Landry (LAN/WiFi)

**Comment by juddin927** [comment]
Had a meeting with Mark L, discussed the issue in details. agreed that we should seek more evidence to ascertain the issue. Following actions were considered going forward.

**Testing:** Implement a temporary configuration change on a switch to potentially clear any cached DHCP server IP information.
**Packet Capture:** Analyze network traffic through packet capture to determine the source of the differing DHCP server IP addresses.
**Vodafone Clarification:** Seek confirmation from Vodafone regarding IP relay functionality for the specific site and investigate any discrepancies in DHCP server IP assignments.

**Comment by tomwells98** [comment]
https://dsdmoj.atlassian.net/browse/ND-89?atlOrigin=eyJpIjoiNmEwNmFjZGEzYmY5NDNiYTlkMjk0YTA0ZWZhYzU2OGUiLCJwIjoiaiJ9
