### ISSUE TITLE
Review Onboarding Checklist Page

### ISSUE THREAD

**Issue by NNavickas1** [ministryofjustice/nvvs-devops#647]
[Onboarding Checklist Page](https://ministryofjustice.github.io/nvvs-devops/documentation/team-guide/team-onboarding-checklist.html#onboarding-checklist) is ready to be reviewed, to ensure it contains the most up to date information to facilitate a smooth onboarding

**Comment by sb21460** [comment]
The checklist needs to be amended to separate steps like Admin account(@justiceuk.onmicrosoft.com) which are specific windows user section , from MAC users.

**Comment by sb21460** [comment]
Updated the Onboarding Checklist page. Waiting for review to merge and close.
