### ISSUE TITLE
SPIKE 🕵️‍♂️ S3 buckets should prohibit public read access

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops#71]
Checks if your S3 buckets allow public read access by evaluating the Block Public Access settings, the bucket policy, and the bucket access check list (ACL).

Source
AWS Security Hub
Security Hub control ID: S3.2

Alert Criteria
Red: Critical or High. Security Hub control failed.

Recommended Action
Follow the Security Hub documentation to fix the issue.

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/71?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by darey-io** [comment]
S3 buckets identified to have public settings turned on in production is documented here. https://docs.google.com/spreadsheets/d/1xloSiGWyZfFW2QFB35QHWeEMt0QU4IihWT8rM6L0xk4/edit?usp=sharing

**Comment by darey-io** [comment]
Had a call with Jahir and discovered that some of the buckets actually have ACL configuration that doesn't require an update to the S3 buckets, even though the "Block all public access" setting is turned off. As we can see in the screenshot <img width="1249" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVB1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b94967a2d804ef144640bb7f87a333d0ad873db0/image.png" alt="image.png" />

**Comment by darey-io** [comment]
Decided to pull out a more robust report using python, rather than manually going through the buckets.

`import boto3
import pandas as pd
from botocore.exceptions import ClientError

def check_public_access(bucket_name, s3_client):
    ####### Initialize public access flag
    public_access = False

    ######## Check bucket policy
    try:
        policy = s3_client.get_bucket_policy(Bucket=bucket_name)
        # Check for public access in the policy (simplified check)
        if '"Principal":"*"' in policy['Policy']:
            public_access = True
    except ClientError as e:
        if e.response['Error']['Code'] != 'NoSuchBucketPolicy':
            raise

    ######## Check public access block settings
    try:
        access_block = s3_client.get_public_access_block(Bucket=bucket_name)
        if not all(access_block['PublicAccessBlockConfiguration'].values()):
            public_access = True
    except ClientError as e:
        if e.response['Error']['Code'] != 'NoSuchPublicAccessBlockConfiguration':
            raise

    return public_access

def list_buckets_and_acls():
    s3_client = boto3.client('s3')
    response = s3_client.list_buckets()

    report_data = []

    for bucket in response['Buckets']:
        bucket_name = bucket['Name']

        acl = s3_client.get_bucket_acl(Bucket=bucket_name)

        public_access = check_public_access(bucket_name, s3_client)
        update_acl = "Yes" if public_access else "No"

        report_data.append({
            "Bucket Name": bucket_name,
            "ACL": str(acl['Grants']),
            "Update ACL to Disallow Public Access": update_acl
        })

    ######## Create DataFrame
    df = pd.DataFrame(report_data)

    ######## Save to Excel
    df.to_excel("s3_bucket_report.xlsx", index=False)

if __name__ == "__main__":
    list_buckets_and_acls()
`

**Comment by darey-io** [comment]
Attached is the report that shows the full view with a column that tells if each bucket needs to "Update ACL to Disallow Public Access" If there is a column with a "yes" then we need to update the bucket setting.

Production - https://docs.google.com/spreadsheets/d/1sKPJ1NV2-WY9_Ai6-9V4ObJ9i9MlQYO_/edit?usp=sharing&ouid=115175937966224608714&rtpof=true&sd=true

**Comment by darey-io** [comment]
**nvvs-devops-monitor-eks-development-thanos-storage** in Development and Pre-production will require  manual update since the infrastructure does not exist except the s3 bucket. while the production goes through the terraform code

**Comment by darey-io** [comment]
All buckets addressed as required except the staff-external-dynamic-* buckets which has been confirmed should be public by design

<img width="1046" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6712fd5d876695bf520b7b53abedd0d7a814187/image.png" alt="image.png" />
