### ISSUE TITLE
🕵️‍♂️ Security Groups - Specific Ports Unrestricted

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops#72]
Checks security groups for rules that allow unrestricted access (0.0.0.0/0) to specific ports. Unrestricted access increases opportunities for malicious activity (hacking, denial-of-service attacks, loss of data). The ports with highest risk are flagged red, and those with less risk are flagged yellow. Ports flagged green are typically used by applications that require unrestricted access, such as HTTP and SMTP.
If you have intentionally configured your security groups in this manner, we recommend using additional security measures to secure your infrastructure (such as IP tables).

Note: This check only evaluates security groups that you create and their inbound rules for IPv4 addresses. Security groups created by AWS Directory Services are flagged as red or yellow, but they don’t pose a security risk and can be safely ignored or excluded. For more information, see the Trusted Advisor FAQ.

Alert Criteria
Green: Access to port 80, 25, 443, or 465 is unrestricted.
Red: Access to port 20, 21, 1433, 1434, 3306, 3389, 4333, 5432, or 5500 is unrestricted.
Yellow: Access to any other port is unrestricted.

Recommended Action
Restrict access to only those IP addresses that require it. To restrict access to a specific IP address, set the suffix to /32 (for example, 192.0.2.10/32). Be sure to delete overly permissive rules after creating rules that are more restrictive.

Additional Resources
Amazon EC2 Security Groups
List of TCP and UDP port numbers (Wikipedia)
Classless Inter-Domain Routing (Wikipedia)

**Comment by Gary-H9** [comment]
Examined TA, verified usage and excluded results relating to the following:
- [ ] Dev 
- [ ] PreProd
- [ ] Prod

`acohen` terraform namespace in Dev needs to be deleted to remove redundant items created in [this](https://github.com/ministryofjustice/staff-device-logging-infrastructure) repo.

**Comment by mitchdawson1982** [comment]
Forwarded remaining groups over to the IGS PM Dotun for review and resolution.

**Comment by Gary-H9** [comment]
Marked `SG_Public` group to be excluded in TA in prep and prod, doesn't appear in Dev. The SG Private group is also not mentioned.
