### ISSUE TITLE
🕵️‍♀️ Security groups should not allow unrestricted access to ports with high risk

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops#74]
Checks if unrestricted incoming traffic for the security groups is accessible to the specified ports [3389, 20, 23, 110, 143, 3306, 8080, 1433, 9200, 9300, 25, 445, 135, 21, 1434, 4333, 5432, 5500, 5601, 22 ] that have the highest risk. This check passes when none of the rules in a security group allow ingress traffic from 0.0.0.0/0 for the listed ports.

Source
AWS Security Hub
Security Hub control ID: EC2.19

Alert Criteria
Red: Critical or High. Security Hub control failed.

Recommended Action
Follow the Security Hub documentation to fix the issue.

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/74?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by Gary-H9** [comment]
We have removed a number of redundant rules from Dev/Prep/Prod. I won't list these here but TA should no longer pick them up (when refreshed) as they don't exist.

**Comment by mitchdawson1982** [comment]
NVVS Devops Team have reviewed all infrastructure platforms that we are responsible for and validated required rules, cleaning up where necessary. We have flagged security groups that are currently non compliant with the appropriate teams.

**Comment by Gary-H9** [comment]
We've gathered some information which we're going to feed back to other teams in the network space to hopefully clean up Dev further.
