### ISSUE TITLE
🔐 Enrol our AWS accounts into Org policy to disable Root

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/nvvs-devops#93]
## User Story

As a CloudOps Engineer
I want to disable all AWS root accounts
So that our products are safe

## Value / Purpose

- increase the security posture on our AWS accounts

## Additional Information

Our accounts will be enrolled in this policy
https://github.com/ministryofjustice/aws-root-account/blob/main/management-account/terraform/organizations-policy-service-control.tf#L46

## Definition of Done (DoD)

Our accounts are all added to 
`ministryofjustice/aws-root-account` service control policy which will disable `root` account

Checklist for definition of done and acceptance criteria, example below (optional).

- [ ] Update our internal documentation on process to gain access to via breakglass
- [ ] Another team member has reviewed 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/93?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by Gary-H9** [comment]
Note the use of Shared Services account in relation to CodePipelines.

**Comment by smjmoj** [comment]
Looking into what we need to do here.
Reached out to @bagg3rs on Slack for some info.

**Comment by smjmoj** [comment]
Started request for 1Password account for access to root account.
